export const CATEGORIES = ["All","Action","Arcade","Multiplayer","Platformer","Puzzle","Racing","RPG","Shooter","Sports","Strategy","Survival","Adventure","Simulation"];

export const GAMES = [
// ── Slope family ───────────────────────────────────────────────
  { id:"slope",             title:"Slope",                   category:"Racing",      tags:["ball","speed","3d","endless","neon"],          thumbnail:"/logos/slope.jpg",          embedPath:"/games/slope.html",          description:"Race a ball down a neon slope at breakneck speed. One mistake and it's over.",      featured:true,  controls:"Arrow keys / WASD" },
  { id:"slopeplus",         title:"Slope+",                  category:"Racing",      tags:["ball","speed","3d","endless"],                  thumbnail:"/logos/slopeplus.png",       embedPath:"/games/slopeplus.html",      description:"The harder, faster version of Slope with extra obstacles.",                          featured:false, controls:"Arrow keys" },
  { id:"snowrider",         title:"Snow Rider 3D",           category:"Racing",      tags:["snow","sled","3d","endless","winter"],           thumbnail:"/logos/snowrider.jpg",       embedPath:"/games/snowrider.html",      description:"Dodge trees and rocks as you sled down an endless snowy mountain.",                  featured:true,  controls:"Arrow keys" },
  { id:"drifthunters",      title:"Drift Hunters",           category:"Racing",      tags:["drift","car","3d","upgrade"],                   thumbnail:"/logos/drifthunters.jpeg",   embedPath:"/games/drifthunters.html",   description:"Drift around tracks and earn cash to upgrade your ride.",                            featured:true,  controls:"WASD + Space" },
  { id:"motox3m",           title:"Moto X3M",                category:"Racing",      tags:["bike","stunt","physics"],                       thumbnail:"/logos/motox3m.png",         embedPath:"/games/motox3m.html",        description:"Pull off insane stunts on a physics-powered dirt bike.",                             featured:false, controls:"Arrow keys" },
  { id:"getaway",           title:"Getaway Shootout",        category:"Multiplayer", tags:["2player","ragdoll","race","funny"],              thumbnail:"/logos/getaway.png",         embedPath:"/games/getaway.html",        description:"Two players race to the getaway vehicle using chaotic physics.",                     featured:true,  controls:"WASD + P/O" },

  // ── 1v1 / Shooter ──────────────────────────────────────────────
  { id:"1v1lol",            title:"1v1.lol",                 category:"Shooter",     tags:["build","shoot","battle royale","multiplayer"],  thumbnail:"/logos/1v1.jpeg",            embedPath:"/games/1v1lol.html",         description:"Build structures and outshoot opponents in this fast-paced battle.",                 featured:true,  controls:"WASD + Mouse" },
  { id:"rooftopsnipers",    title:"Rooftop Snipers",         category:"Multiplayer", tags:["2player","sniper","physics","ragdoll"],          thumbnail:"/logos/rooftop.png",         embedPath:"/games/rooftopsnipers.html", description:"Knock your opponent off the rooftop with one well-placed shot.",                     featured:true,  controls:"W + P to shoot" },
  { id:"rooftopsnipers2",   title:"Rooftop Snipers 2",       category:"Multiplayer", tags:["2player","sniper","physics","sequel"],           thumbnail:"/logos/rooftop2.jpeg",       embedPath:"/games/rooftopsnipers2.html",description:"More maps and guns in the sniper rooftop sequel.",                                   featured:false, controls:"W + P to shoot" },
  { id:"funnyshooter2",     title:"Funny Shooter 2",         category:"Shooter",     tags:["fps","3d","silly","arena"],                     thumbnail:"/logos/funny-shooter-2.jpg", embedPath:"/games/funnyshooter2.html",  description:"FPS chaos where you shoot goofy ragdoll enemies in arenas.",                         featured:false, controls:"WASD + Mouse" },
  { id:"csgo",              title:"CS:GO Classic",           category:"Shooter",     tags:["fps","counterstrike","arena","retro"],           thumbnail:"/logos/csgo.jpeg",           embedPath:"/games/csgo.html",           description:"Classic Counter-Strike gameplay in your browser.",                                   featured:false, controls:"WASD + Mouse" },
  { id:"codmw4",            title:"CoD: Modern Warfare 4",   category:"Shooter",     tags:["fps","cod","multiplayer","action"],              thumbnail:"/logos/codmw4.png",          embedPath:"/games/codmw4.html",         description:"Modern Warfare-style FPS action in the browser.",                                    featured:false, controls:"WASD + Mouse" },

  // ── Platformer ─────────────────────────────────────────────────
  { id:"celeste",           title:"Celeste",                 category:"Platformer",  tags:["indie","hard","pixel","precision","mountain"],   thumbnail:"/logos/celeste.jpg",         embedPath:"/games/celeste.html",        description:"A brutally precise platformer about climbing a mountain and facing your inner demons.",featured:true, controls:"Arrow keys + Z/X/C" },
  { id:"hollow",            title:"Hollow Knight",           category:"Adventure",   tags:["metroidvania","indie","bug","dark","boss"],      thumbnail:"/logos/hollow.jpg",          embedPath:"/games/hollow.html",         description:"Explore a vast underground kingdom of insects in this acclaimed metroidvania.",      featured:true,  controls:"Arrow keys + Z/X/C" },
  { id:"silksong",          title:"Hollow Knight: Silksong", category:"Adventure",   tags:["metroidvania","sequel","silk","boss"],           thumbnail:"/logos/silksong.jpg",        embedPath:"/games/silksong.html",       description:"Play as Hornet in this anticipated sequel to Hollow Knight.",                        featured:true,  controls:"Arrow keys + Z/X/C" },
  { id:"ovo",               title:"OvO",                     category:"Platformer",  tags:["parkour","speedrun","minimalist","stickman"],    thumbnail:"/logos/ovo.png",             embedPath:"/games/ovo.html",            description:"Ultra-smooth stickman platformer built for speedrunning.",                           featured:true,  controls:"Arrow keys" },
  { id:"ovo2",              title:"OvO 2",                   category:"Platformer",  tags:["parkour","speedrun","sequel","stickman"],        thumbnail:"/logos/ovo2.webp",           embedPath:"/games/ovo2.html",           description:"Even more levels and mechanics in the parkour platformer sequel.",                   featured:false, controls:"Arrow keys" },
  { id:"vex",               title:"Vex",                     category:"Platformer",  tags:["stickman","obstacle","hard","precise"],          thumbnail:"/logos/vex.png",             embedPath:"/games/vex.html",            description:"Traverse deadly obstacle courses as a nimble stickman.",                             featured:false, controls:"WASD + Arrow keys" },
  { id:"vex2",              title:"Vex 2",                   category:"Platformer",  tags:["stickman","obstacle","hard","sequel"],           thumbnail:"/logos/vex2.jpeg",           embedPath:"/games/vex2.html",           description:"More devious traps and levels in the stickman obstacle series.",                     featured:false, controls:"WASD + Arrow keys" },
  { id:"vex3",              title:"Vex 3",                   category:"Platformer",  tags:["stickman","obstacle","hard","sequel"],           thumbnail:"/logos/vex3.png",             embedPath:"/games/vex3.html",           description:"Vex 3 brings water levels and new obstacles to the deadly series.",                  featured:false, controls:"WASD + Arrow keys" },
  { id:"fancypantsadventure",title:"Fancy Pants Adventure",  category:"Platformer",  tags:["stick","fluid","cartoon","classic"],             thumbnail:"/logos/fancy.png",           embedPath:"/games/fancypantsadventure.html",description:"Run and flip through hand-drawn worlds as the iconic Fancy Pants Man.",            featured:false, controls:"Arrow keys + S" },
  { id:"redball",           title:"Red Ball",                category:"Platformer",  tags:["ball","roll","physics","cute"],                  thumbnail:"/logos/redball.webp",        embedPath:"/games/redball.html",        description:"Roll the red ball through puzzle-platformer levels.",                               featured:false, controls:"Arrow keys" },
  { id:"supermario64",      title:"Super Mario 64",          category:"Platformer",  tags:["mario","nintendo","3d","classic","n64"],         thumbnail:"/logos/supermario64.jpg",    embedPath:"/games/supermario64.html",   description:"The legendary 3D platformer that defined a generation.",                            featured:true,  controls:"WASD + Mouse" },
  { id:"mariocombat",       title:"Mario Combat",            category:"Platformer",  tags:["mario","beat em up","classic"],                  thumbnail:"/logos/mariocombat.png",     embedPath:"/games/mariocombat.html",    description:"Mario takes on waves of Goombas in this retro beat-em-up.",                         featured:false, controls:"Arrow keys + A/S" },
  { id:"sonicthehedgehog",  title:"Sonic the Hedgehog",      category:"Platformer",  tags:["sonic","sega","speed","classic","retro"],        thumbnail:"/logos/sonic.jpeg",          embedPath:"/games/sonicthehedgehog.html",description:"The original speedy blue hedgehog in classic Sega Genesis form.",                  featured:true,  controls:"Arrow keys" },
  { id:"riddleschool",      title:"Riddle School",           category:"Puzzle",      tags:["point click","escape","school","flash"],         thumbnail:"/logos/riddle.jpeg",         embedPath:"/games/riddleschool.html",   description:"Point-and-click your way out of school in this beloved flash classic.",             featured:false, controls:"Mouse" },
  { id:"noobsteveparkour",  title:"Noob Steve Parkour",      category:"Platformer",  tags:["minecraft","parkour","pixel","noob"],            thumbnail:"/logos/noobsteveparkour.png",embedPath:"/games/noob-steve-parkour/index.html",description:"Parkour through Minecraft-inspired levels as Noob Steve.",                     featured:false, controls:"WASD + Space" },
  { id:"icedodo",           title:"Ice Dodo",                category:"Arcade",      tags:["cute","ice","endless","bird"],                   thumbnail:"/logos/icedodo.jpg",         embedPath:"/games/icedodo.html",        description:"Guide a cute dodo bird through icy obstacles.",                                     featured:false, controls:"Tap / Click" },

  // ── Retro Bowl family ──────────────────────────────────────────
  { id:"retrobowl",         title:"Retro Bowl",              category:"Sports",      tags:["football","retro","pixel","nfl","management"],   thumbnail:"/logos/unnamed.png",         embedPath:"/games/retrobowl.html",      description:"Manage and play a retro-style American football team to glory.",                    featured:true,  controls:"Mouse + Tap" },
  { id:"retrobowlcollege",  title:"Retro Bowl College",      category:"Sports",      tags:["football","college","retro","pixel"],            thumbnail:"/logos/retrobowl2.webp",     embedPath:"/games/retrobowlcollege.html",description:"Take a college football program to a national championship.",                     featured:false, controls:"Mouse + Tap" },

  // ── Sports ─────────────────────────────────────────────────────
  { id:"basketbros",        title:"Basketball Bros",         category:"Sports",      tags:["basketball","2player","funny","ragdoll"],        thumbnail:"/logos/basketbros.jpg",      embedPath:"/games/basketbros.html",     description:"Dunk on your friends in this hilarious 2-player basketball brawler.",               featured:true,  controls:"WASD + Arrow keys" },
  { id:"basketrandom",      title:"Basketball Random",       category:"Multiplayer", tags:["basketball","random","2player","ragdoll"],       thumbnail:"/logos/basket.png",          embedPath:"/games/basketrandom.html",   description:"Chaotic basketball with random physics and characters every round.",                 featured:false, controls:"W + Up" },
  { id:"basketstars",       title:"Basket Stars",            category:"Sports",      tags:["basketball","swipe","mobile","street"],          thumbnail:"/logos/basketstars.jpg",     embedPath:"/games/basketstars.html",    description:"Score creative baskets with swipe shots in Basket Stars.",                          featured:false, controls:"Mouse drag" },
  { id:"boxingrandom",      title:"Boxing Random",           category:"Multiplayer", tags:["boxing","2player","ragdoll","physics","funny"],  thumbnail:"/logos/boxing.png",          embedPath:"/games/boxingrandom.html",   description:"Two ragdoll boxers fight with random physics in every round.",                       featured:false, controls:"W + Up" },
  { id:"volleyrandom",      title:"Volleyball Random",       category:"Multiplayer", tags:["volleyball","2player","ragdoll","physics"],      thumbnail:"/logos/volley.png",          embedPath:"/games/volleyrandom.html",   description:"Random physics volleyball with hilarious ragdoll characters.",                      featured:false, controls:"W + Up" },
  { id:"footbros",          title:"Football Bros",           category:"Sports",      tags:["football","2player","soccer","brawl"],           thumbnail:"/logos/footbros.jpg",        embedPath:"/games/footbros.html",       description:"Fast-paced 2-player football brawler with power moves.",                            featured:false, controls:"WASD + Arrow keys" },
  { id:"basebros",          title:"Base Bros",               category:"Sports",      tags:["baseball","2player","ragdoll"],                  thumbnail:"/logos/basebros.jpg",        embedPath:"/games/basebros.html",       description:"Swing for the fences in this 2-player baseball brawler.",                           featured:false, controls:"WASD + Arrow keys" },
  { id:"gladd",             title:"Gladdiahoppers",          category:"Multiplayer", tags:["gladiator","2player","arena","fight"],           thumbnail:"/logos/gladdihoppers.jpg",   embedPath:"/games/gladd.html",          description:"Fight as gladiators in this chaotic 2-player arena brawler.",                       featured:false, controls:"WASD + Arrow keys" },
  { id:"fifa11",            title:"FIFA 11",                 category:"Sports",      tags:["soccer","fifa","classic","football"],            thumbnail:"/logos/fifa11.jpg",          embedPath:"/games/fifa11.html",         description:"Classic FIFA 11 soccer in your browser.",                                           featured:false, controls:"Arrow keys + A/S/D" },
  { id:"supa",              title:"Super Smash Bros",        category:"Multiplayer", tags:["smash","nintendo","fight","2player","brawl"],    thumbnail:"/logos/supersmashbros.jpg",  embedPath:"/games/supa.html",           description:"Play Super Smash Bros characters in a browser brawler.",                            featured:true,  controls:"WASD + Arrow keys" },

  // ── Subway Surfers ─────────────────────────────────────────────
  { id:"subwaysurfersmiami",title:"Subway Surfers: Miami",   category:"Arcade",      tags:["runner","subway","mobile","endless","surf"],     thumbnail:"/logos/subwaymiami.webp",    embedPath:"/games/subwaysurfersmiami.html",description:"Surf through Miami's vibrant subway system.",                                    featured:true,  controls:"Arrow keys / Swipe" },
  { id:"subwaysurferswinterholiday",title:"Subway Surfers: Winter",category:"Arcade", tags:["runner","subway","winter","endless","surf"],    thumbnail:"/logos/wintersurf.webp",     embedPath:"/games/subwaysurferswinterholiday.html",description:"The classic runner in a snowy winter holiday setting.",                       featured:false, controls:"Arrow keys / Swipe" },

  // ── Puzzle ─────────────────────────────────────────────────────
  { id:"geometrydash",      title:"Geometry Dash",           category:"Arcade",      tags:["rhythm","jump","music","hard","timing"],         thumbnail:"/logos/geometry.png",        embedPath:"/games/geometrydash.html",   description:"Jump to the rhythm and dodge obstacles in this music-based runner.",                featured:true,  controls:"Click / Spacebar" },
  { id:"geodash_gba_port",  title:"Geometry Dash GBA",       category:"Arcade",      tags:["rhythm","retro","gba","geometry"],               thumbnail:"/logos/geodashdemake.png",   embedPath:"/games/geodash_gba_port/index.html",description:"Geometry Dash reimagined as a Game Boy Advance demake.",                      featured:false, controls:"Click / Z" },
  { id:"cookie",            title:"Cookie Clicker",          category:"Simulation",  tags:["idle","clicker","incremental","cookies"],        thumbnail:"/logos/cookieclicker.jpg",   embedPath:"/games/cookie.html",         description:"Click cookies to build the biggest cookie empire possible.",                        featured:true,  controls:"Mouse click" },
  { id:"tinyfishing",       title:"Tiny Fishing",            category:"Simulation",  tags:["fishing","idle","chill","cast"],                  thumbnail:"/logos/tiny-fishing-square-icon.png",embedPath:"/games/tinyfishing.html",description:"Cast your line and reel in tiny fish to upgrade your gear.",                  featured:true,  controls:"Mouse click" },
  { id:"linerider",         title:"Line Rider",              category:"Puzzle",      tags:["draw","physics","sled","creative","sandbox"],    thumbnail:"/logos/linerider.png",       embedPath:"/games/linerider.html",      description:"Draw lines and watch a sledder ride them with realistic physics.",                  featured:false, controls:"Mouse draw" },
  { id:"fruitninja",        title:"Fruit Ninja",             category:"Arcade",      tags:["slice","fruit","swipe","mobile","reflex"],       thumbnail:"/logos/fruit.webp",          embedPath:"/games/fruitninja.html",     description:"Slice fruit before it falls off the screen. Miss three and you're done.",           featured:false, controls:"Mouse swipe" },
  { id:"nutsnbolts",        title:"Nuts n Bolts",            category:"Puzzle",      tags:["physics","puzzle","screw","wrench"],              thumbnail:"/logos/nuts.png",            embedPath:"/games/nutsnbolts.html",     description:"Solve physics-based puzzles by fitting nuts and bolts together.",                   featured:false, controls:"Mouse" },
  { id:"badtime",           title:"Undertale: Bad Time",     category:"RPG",         tags:["undertale","sans","boss","bullet hell","dodge"], thumbnail:"/logos/badtime.webp",        embedPath:"/games/badtime.html",        description:"Survive Sans's legendary bad time boss fight from Undertale.",                      featured:true,  controls:"Arrow keys + Z/X" },
  { id:"unfairundyne",      title:"Unfair Undyne",           category:"RPG",         tags:["undertale","undyne","boss","dodge","hard"],      thumbnail:"/logos/Undyne_face.webp",    embedPath:"/games/unfairundyne.html",   description:"Face an impossibly hard version of Undyne's spear attacks.",                        featured:false, controls:"Arrow keys + Z/X" },
  { id:"webglfluidsimulation",title:"WebGL Fluid Simulation",category:"Simulation",  tags:["fluid","interactive","sandbox","art","chill"],   thumbnail:"/logos/webglfluidsimulation.png",embedPath:"/games/webgl-fluid-simulation/index.html",description:"Mesmerizing interactive fluid simulation you can swirl with your finger.", featured:false, controls:"Mouse / Touch" },

  // ── Among Us / IO ──────────────────────────────────────────────
  { id:"amongus",           title:"Among Us",                category:"Multiplayer", tags:["impostor","social","deduction","space","vote"], thumbnail:"/logos/Among_Us.webp",       embedPath:"/games/amongus.html",        description:"Find the impostor aboard the spaceship before it's too late.",                      featured:true,  controls:"WASD + Click" },
  { id:"agario",            title:"Agar.io",                 category:"Multiplayer", tags:["io","blob","eat","grow","multiplayer","online"],  thumbnail:"/logos/agario.jpg",         embedPath:"/games/agario.html",         description:"Eat smaller cells to grow bigger while avoiding larger ones.",                      featured:true,  controls:"Mouse" },
  { id:"paperio",           title:"Paper.io",                category:"Multiplayer", tags:["io","territory","snake","multiplayer","online"], thumbnail:"/logos/paperio.jpg",         embedPath:"/games/paperio.html",        description:"Claim territory and cut off rivals in this addictive .io game.",                    featured:false, controls:"Arrow keys" },
  { id:"crossyroads",       title:"Crossy Road",             category:"Arcade",      tags:["frogger","hop","mobile","endless","cute"],       thumbnail:"/logos/Crossy_Road_icon.jpeg",embedPath:"/games/crossyroads.html",   description:"Hop across roads and rivers endlessly without getting squished.",                   featured:false, controls:"Arrow keys / WASD" },

  // ── Indie / Narrative ──────────────────────────────────────────
  { id:"omori",             title:"Omori",                   category:"RPG",         tags:["rpg","indie","horror","narrative","dream"],      thumbnail:"/logos/omori.jpeg",          embedPath:"/games/omori.html",          description:"Explore a surreal dream world hiding deep secrets in this indie RPG.",              featured:true,  controls:"Arrow keys + Z/X/C" },
  { id:"deltarune",         title:"Deltarune",               category:"RPG",         tags:["undertale","rpg","kris","dark world","indie"],   thumbnail:"/logos/deltarune.webp",      embedPath:"/games/deltarune.html",      description:"Undertale creator Toby Fox's latest RPG – chapters 1 & 2.",                        featured:true,  controls:"Arrow keys + Z/X" },
  { id:"oneshot",           title:"OneShot",                 category:"Adventure",   tags:["rpg","meta","lightbulb","puzzle","narrative"],   thumbnail:"/logos/oneshot.jpg",         embedPath:"/games/oneshot.html",        description:"A game that knows you're playing it. You only get one shot.",                       featured:false, controls:"Arrow keys + Z" },
  { id:"yume",              title:"Yume Nikki",              category:"Adventure",   tags:["rpg","surreal","dream","explore","japanese"],    thumbnail:"/logos/yume-nikki.webp",     embedPath:"/games/yume.html",           description:"Wander through a dream-girl's surreal, disturbing subconscious.",                  featured:false, controls:"Arrow keys + Z" },
  { id:"bind",              title:"The Binding of Isaac",    category:"Roguelike",   tags:["roguelike","dungeon","dark","random","boss"],    thumbnail:"/logos/binding.jpg",         embedPath:"/games/bind.html",           description:"Descend into a procedurally generated basement full of monsters.",                  featured:true,  controls:"WASD + Arrow keys" },
  { id:"celeste2",          title:"Celeste Classic",         category:"Platformer",  tags:["pico8","celeste","hard","pixel","precision"],    thumbnail:"/logos/celeste.jpg",         embedPath:"/games/celeste.html",        description:"The original PICO-8 prototype that became the full game.",                          featured:false, controls:"Arrow keys + Z/X" },

  // ── FNAF ───────────────────────────────────────────────────────
  { id:"fnaf",              title:"Five Nights at Freddy's", category:"Survival",    tags:["horror","fnaf","animatronic","night","scary"],   thumbnail:"/logos/fnaf.jpg",            embedPath:"/games/fnaf.html",           description:"Survive five nights as a security guard at Freddy Fazbear's Pizza.",                featured:true,  controls:"Mouse" },
  { id:"fnaf2",             title:"FNAF 2",                  category:"Survival",    tags:["horror","fnaf","animatronic","sequel","scary"],  thumbnail:"/logos/fnaf2.jpg",           embedPath:"/games/fnaf2.html",          description:"The old animatronics are back and there are new ones too.",                          featured:false, controls:"Mouse" },
  { id:"fnaf3",             title:"FNAF 3",                  category:"Survival",    tags:["horror","fnaf","springtrap","sequel"],           thumbnail:"/logos/fnaf3.jpg",           embedPath:"/games/fnaf3.html",          description:"One animatronic remains in the FNAF horror series: Springtrap.",                    featured:false, controls:"Mouse" },
  { id:"fnaf4",             title:"FNAF 4",                  category:"Survival",    tags:["horror","fnaf","nightmare","bedroom","sequel"],  thumbnail:"/logos/fnaf4.jpg",           embedPath:"/games/fnaf4.html",          description:"The most frightening FNAF yet – nightmare animatronics in your home.",              featured:false, controls:"Mouse" },
  { id:"baldibasics",       title:"Baldi's Basics",          category:"Survival",    tags:["horror","baldi","school","teacher","creepy"],   thumbnail:"/logos/baldi.png",           embedPath:"/games/baldibasics.html",    description:"Collect notebooks while avoiding the terrifyingly fast Baldi.",                     featured:true,  controls:"Mouse + WASD" },
  { id:"granny",            title:"Granny",                  category:"Survival",    tags:["horror","escape","stealth","granny"],           thumbnail:"/logos/granny.jpg",          embedPath:"/games/granny.html",         description:"Escape the house without waking up Granny. She hears everything.",                  featured:false, controls:"Mouse + WASD" },
  { id:"granny2",           title:"Granny 2",                category:"Survival",    tags:["horror","escape","stealth","granny","sequel"],   thumbnail:"/logos/granny2.jpg",         embedPath:"/games/granny2.html",        description:"Two enemies now stalk you in this expanded horror escape sequel.",                   featured:false, controls:"Mouse + WASD" },

  // ── Pokemon ─────────────────────────────────────────────────────
  { id:"pokemonemerald",    title:"Pokemon Emerald",         category:"RPG",         tags:["pokemon","gba","hoenn","emerald","classic"],    thumbnail:"/logos/emerald.jpg",         embedPath:"/games/pokemonemerald.html", description:"The definitive Hoenn region Pokemon experience on Game Boy Advance.",               featured:true,  controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonfirered",    title:"Pokemon Fire Red",        category:"RPG",         tags:["pokemon","gba","kanto","firered","classic"],    thumbnail:"/logos/pokefire.jpg",         embedPath:"/games/pokemonfirered.html", description:"Experience the Kanto region remake for Game Boy Advance.",                          featured:false, controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonleafgreen",  title:"Pokemon Leaf Green",      category:"RPG",         tags:["pokemon","gba","kanto","leafgreen"],            thumbnail:"/logos/leafgreen.jpg",        embedPath:"/games/pokemonleafgreen.html",description:"The Leaf Green version of the Kanto region remake.",                              featured:false, controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonruby",       title:"Pokemon Ruby",            category:"RPG",         tags:["pokemon","gba","hoenn","ruby"],                 thumbnail:"/logos/ruby.png",             embedPath:"/games/pokemonruby.html",    description:"Explore the Hoenn region for the first time in Pokemon Ruby.",                      featured:false, controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonstadium",    title:"Pokemon Stadium",         category:"RPG",         tags:["pokemon","n64","stadium","3d","battle"],        thumbnail:"/logos/stadium.webp",         embedPath:"/games/pokemonstadium.html", description:"Battle in 3D in the classic Nintendo 64 Pokemon Stadium.",                          featured:false, controls:"Arrow keys + Z/X" },
  { id:"pokemonunbound",    title:"Pokemon Unbound",         category:"RPG",         tags:["pokemon","hack","gba","custom","hard"],         thumbnail:"/logos/pokeunbound.webp",     embedPath:"/games/pokemonunbound.html", description:"A fan-made Pokemon hack with a new region, story, and 800+ Pokemon.",               featured:true,  controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonemeraldrg",  title:"Pokemon Emerald Rogue",   category:"RPG",         tags:["pokemon","roguelike","emerald","hack"],         thumbnail:"/logos/rouge.png",            embedPath:"/games/pokemonemeraldrg.html",description:"Roguelike Pokemon Emerald with randomized routes and items every run.",         featured:false, controls:"Arrow keys + Z/X/A/S" },

  // ── Retro / Classic ─────────────────────────────────────────────
  { id:"doom",              title:"Doom",                    category:"Shooter",     tags:["fps","retro","demon","classic","id"],            thumbnail:"/logos/doom.jpeg",           embedPath:"/games/doom.html",           description:"The original 1993 FPS that defined first-person shooters.",                         featured:true,  controls:"WASD + Mouse" },
  { id:"metal",             title:"Metal Slug",              category:"Action",      tags:["run n gun","retro","arcade","classic","neo geo"],thumbnail:"/logos/metal.jpg",           embedPath:"/games/metal.html",          description:"Run, gun, and rescue POWs in this legendary arcade run-n-gun.",                     featured:true,  controls:"Arrow keys + A/S/D" },
  { id:"mariokart64",       title:"Mario Kart 64",           category:"Racing",      tags:["mario","n64","kart","classic","multiplayer"],    thumbnail:"/logos/mariokart.jpeg",       embedPath:"/games/mariokart64.html",    description:"Race as Mario characters on the iconic N64 tracks.",                                featured:true,  controls:"Arrow keys + Z/X" },
  { id:"metroidfusion",     title:"Metroid Fusion",          category:"Adventure",   tags:["metroid","gba","samus","fusion","metroidvania"],  thumbnail:"/logos/metroid.jpg",        embedPath:"/games/metroidfusion.html",  description:"Samus hunts parasitic X organisms aboard a research station.",                      featured:false, controls:"Arrow keys + Z/X/A" },
  { id:"ocarina",           title:"Ocarina of Time",         category:"Adventure",   tags:["zelda","n64","link","ocarina","3d","classic"],   thumbnail:"/logos/ocorina.jpg",          embedPath:"/games/ocarina.html",        description:"Link's first 3D adventure to stop Ganondorf from conquering Hyrule.",               featured:true,  controls:"WASD + Mouse" },
  { id:"sonicthehedgehog2", title:"Sonic the Hedgehog",      category:"Platformer",  tags:["sonic","sega","speed","retro","classic"],        thumbnail:"/logos/sonic.jpeg",           embedPath:"/games/sonicthehedgehog.html",description:"Speed through Green Hill Zone in the original Sega classic.",                     featured:false, controls:"Arrow keys" },

  // ── Indie horror / Narrative ───────────────────────────────────
  { id:"silent",            title:"Silent Hill",             category:"Survival",    tags:["horror","fog","ps1","classic","survival"],      thumbnail:"/logos/silent.jpg",           embedPath:"/games/silent.html",         description:"Wander the fog-covered streets of Silent Hill in the PS1 classic.",                 featured:false, controls:"Arrow keys" },
  { id:"oblivoneve",        title:"Oblivion Eve",            category:"Adventure",   tags:["rpg","indie","dark","oblivion"],                thumbnail:"/logos/oblivion.png",         embedPath:"/games/oblivoneve.html",     description:"An indie RPG inspired by the dark world of Oblivion.",                             featured:false, controls:"Mouse + WASD" },
  { id:"kinder",            title:"Kindergarten",            category:"Adventure",   tags:["dark comedy","school","story","choice","indie"],thumbnail:"/logos/kinder.jpg",           embedPath:"/games/kinder.html",         description:"Survive a very messed-up day at kindergarten.",                                     featured:false, controls:"Mouse + Arrow keys" },
  { id:"kinder2",           title:"Kindergarten 2",          category:"Adventure",   tags:["dark comedy","school","story","sequel","indie"],thumbnail:"/logos/kinder2.jpg",          embedPath:"/games/kinder2.html",        description:"More dark kindergarten chaos in the sequel.",                                       featured:false, controls:"Mouse + Arrow keys" },
  { id:"kinder3",           title:"Kindergarten 3",          category:"Adventure",   tags:["dark comedy","school","story","sequel","indie"],thumbnail:"/logos/kinder3.jpg",          embedPath:"/games/kinder3.html",        description:"The trilogy continues at the most dangerous school ever.",                          featured:false, controls:"Mouse + Arrow keys" },

  // ── Misc Action / Arcade ──────────────────────────────────────
  { id:"ultrakill",         title:"Ultrakill",               category:"Action",      tags:["fps","fast","stylish","cyberpunk","blood"],      thumbnail:"/logos/ultrakill.jpeg",       embedPath:"/games/ultrakill.html",      description:"Feed on blood to heal and go as fast as possible in this stylish FPS.",             featured:true,  controls:"WASD + Mouse" },
  { id:"awesome",           title:"Awesome Tanks 2",         category:"Action",      tags:["tank","top down","shooter","upgrade"],           thumbnail:"/logos/awesome.jpg",          embedPath:"/games/awesome.html",        description:"Blast through levels and upgrade your tank in this top-down shooter.",              featured:false, controls:"WASD + Mouse" },
  { id:"hazard",            title:"Hazard",                  category:"Action",      tags:["shooter","action","top down"],                  thumbnail:"/logos/hazard.png",           embedPath:"/games/hazard.html",         description:"Top-down shooter with hazardous environments.",                                     featured:false, controls:"WASD + Mouse" },
  { id:"karl",              title:"Karl",                    category:"Arcade",      tags:["puzzle","funny","physics","karl"],               thumbnail:"/logos/karl.jpg",             embedPath:"/games/karl.html",           description:"Help Karl navigate puzzles in this quirky physics game.",                           featured:false, controls:"Mouse" },
  { id:"clash",             title:"Clash Royale",            category:"Strategy",    tags:["card","tower defense","supercell","real time"],  thumbnail:"/logos/clash.jpg",            embedPath:"/games/clash.html",          description:"Build decks and destroy the enemy king's tower in real-time card battles.",         featured:false, controls:"Mouse / Touch" },
  { id:"taiseiproject",     title:"Taisei Project",          category:"Shooter",     tags:["bullet hell","touhou","shmup","anime"],          thumbnail:"/logos/taisei.png",           embedPath:"/games/taiseiproject.html",  description:"An open-source Touhou-inspired bullet hell with stunning patterns.",                 featured:false, controls:"Arrow keys + Z/X/Shift" },
  { id:"theycomin",         title:"They Are Coming",         category:"Strategy",    tags:["zombie","tower defense","wave","click"],         thumbnail:"/logos/theyarecoming.jpg",    embedPath:"/games/theycomin.html",      description:"Survive endless waves of zombies using upgrades and strategy.",                      featured:false, controls:"Mouse" },
  { id:"jet",               title:"Jetpack Joyride",         category:"Arcade",      tags:["jetpack","endless","mobile","coins","classic"],  thumbnail:"/logos/jetpack.jpg",          embedPath:"/games/jet.html",            description:"Strap on a jetpack and dodge electric beams in this endless runner.",               featured:true,  controls:"Click / Spacebar" },
  { id:"snow",              title:"Snow Battle",             category:"Action",      tags:["snowball","fight","winter","action"],            thumbnail:"/logos/snowbattle.jpg",       embedPath:"/games/snow.html",           description:"Pelt your opponents with snowballs in an icy arena.",                               featured:false, controls:"Mouse + WASD" },

  // ── Eaglercraft / Minecraft ────────────────────────────────────
  { id:"eaglercraft122",    title:"Eaglercraft 1.22",        category:"Adventure",   tags:["minecraft","browser","survival","build","craft"],thumbnail:"/logos/eagler.png",          embedPath:"/games/eaglercraft122.html", description:"Full Minecraft experience running directly in your browser.",                        featured:true,  controls:"WASD + Mouse" },

  // ── Celeste / Indie ────────────────────────────────────────────
  { id:"fnf",               title:"Friday Night Funkin'",    category:"Arcade",      tags:["rhythm","music","rap","battle","funkin"],       thumbnail:"/logos/fnf.webp",             embedPath:"/games/fnf.html",            description:"Battle musical foes in this rhythm rap showdown.",                                  featured:true,  controls:"Arrow keys / WASD" },
  { id:"bitlife",           title:"BitLife",                 category:"Simulation",  tags:["life","sim","choices","text","casual"],          thumbnail:"/logos/bitlife.png",          embedPath:"/games/bitlife.html",        description:"Live countless virtual lives full of choices in this text-based life sim.",          featured:true,  controls:"Mouse / Touch" },

  // ── New DotGUI extras ─────────────────────────────────────────
  { id:"ballistic-chickens",title:"Ballistic Chickens",      category:"Action",      tags:["chickens","launch","physics","silly","arcade"],  thumbnail:"/logos/ballisticchickens.png",embedPath:"/games/ballistic-chickens/index.html",description:"Launch ballistic chickens at targets in this physics shooter.", featured:false, controls:"Mouse" },
  { id:"ctr",               title:"Crash Team Racing",       category:"Racing",      tags:["crash","kart","ps1","classic","race"],           thumbnail:"/logos/ctr.png",              embedPath:"/games/ctr/index.html",      description:"Race as Crash Bandicoot and friends in the classic kart racer.",                     featured:true,  controls:"Arrow keys + Z/X" },
  { id:"ctr-tr",            title:"CTR: Time Reckoning",     category:"Racing",      tags:["crash","kart","time trial","race"],              thumbnail:"/logos/ctrtr.png",            embedPath:"/games/ctr-tr/index.html",   description:"Time trial version of Crash Team Racing for speedrunners.",                         featured:false, controls:"Arrow keys + Z/X" },
  { id:"ltf3",              title:"Little Town Fishing 3",   category:"Simulation",  tags:["fishing","chill","little town","idle"],          thumbnail:"/logos/ltf3.png",             embedPath:"/games/ltf3/index.html",     description:"Relaxing fishing in Little Town, the third installment.",                           featured:false, controls:"Mouse" },
  { id:"there-is-no-game",  title:"There Is No Game",        category:"Puzzle",      tags:["meta","fourth wall","funny","puzzle","unique"],  thumbnail:"/logos/thereisnogame.png",    embedPath:"/games/there-is-no-game/index.html",description:"A game that insists there is no game. Click around to find out.",            featured:true,  controls:"Mouse + Click" },
  { id:"twitch-tetris",     title:"Twitch Tetris",           category:"Puzzle",      tags:["tetris","block","twitch","classic","puzzle"],    thumbnail:"/logos/twitchtetris.png",     embedPath:"/games/twitch-tetris/index.html",description:"Classic Tetris-style block puzzle with a twist.",                              featured:false, controls:"Arrow keys" },

  // ── Extra popular games ────────────────────────────────────────
  { id:"deltarune-ch2",     title:"Deltarune Ch. 2",         category:"RPG",         tags:["undertale","rpg","sequel","kris","cyber"],       thumbnail:"/logos/deltarune.webp",       embedPath:"/games/deltarune.html",      description:"Chapter 2 continues Kris's journey into the Dark World.",                          featured:false, controls:"Arrow keys + Z/X" },
  { id:"celeste-ch2",       title:"Celeste Classic 2",       category:"Platformer",  tags:["pico8","celeste","sequel","hard","precision"],   thumbnail:"/logos/celeste.jpg",          embedPath:"/games/celeste.html",        description:"The follow-up to the original PICO-8 Celeste classic.",                            featured:false, controls:"Arrow keys + Z/X" },
  { id:"pixel-runner", title:"Pixel Runner", category:"Action", tags:["action","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Pixel%20Runner", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Pixel%20Runner", description:"Play Pixel Runner online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"galaxy-blaster", title:"Galaxy Blaster", category:"Arcade", tags:["arcade","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Galaxy%20Blaster", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Galaxy%20Blaster", description:"Play Galaxy Blaster online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"cave-explorer", title:"Cave Explorer", category:"Puzzle", tags:["puzzle","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Cave%20Explorer", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Cave%20Explorer", description:"Play Cave Explorer online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"neon-dash", title:"Neon Dash", category:"Racing", tags:["racing","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Neon%20Dash", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Neon%20Dash", description:"Play Neon Dash online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"fortress-builder", title:"Fortress Builder", category:"Shooter", tags:["shooter","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Fortress%20Builder", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Fortress%20Builder", description:"Play Fortress Builder online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"space-miner", title:"Space Miner", category:"Strategy", tags:["strategy","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Space%20Miner", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Space%20Miner", description:"Play Space Miner online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"jungle-jump", title:"Jungle Jump", category:"Adventure", tags:["adventure","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Jungle%20Jump", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Jungle%20Jump", description:"Play Jungle Jump online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"ocean-quest", title:"Ocean Quest", category:"Platformer", tags:["platformer","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Ocean%20Quest", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Ocean%20Quest", description:"Play Ocean Quest online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"desert-storm", title:"Desert Storm", category:"Simulation", tags:["simulation","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Desert%20Storm", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Desert%20Storm", description:"Play Desert Storm online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"robo-wars", title:"Robo Wars", category:"RPG", tags:["rpg","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Robo%20Wars", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Robo%20Wars", description:"Play Robo Wars online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"magic-maze", title:"Magic Maze", category:"Sports", tags:["sports","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Magic%20Maze", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Magic%20Maze", description:"Play Magic Maze online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"speed-circuit", title:"Speed Circuit", category:"Survival", tags:["survival","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Speed%20Circuit", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Speed%20Circuit", description:"Play Speed Circuit online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"dino-herd", title:"Dino Herd", category:"Multiplayer", tags:["multiplayer","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Dino%20Herd", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Dino%20Herd", description:"Play Dino Herd online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"star-raider", title:"Star Raider", category:"Action", tags:["action","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Star%20Raider", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Star%20Raider", description:"Play Star Raider online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"dungeon-crawl", title:"Dungeon Crawl", category:"Arcade", tags:["arcade","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Dungeon%20Crawl", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Dungeon%20Crawl", description:"Play Dungeon Crawl online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"turbo-kart", title:"Turbo Kart", category:"Puzzle", tags:["puzzle","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Turbo%20Kart", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Turbo%20Kart", description:"Play Turbo Kart online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"ninja-leap", title:"Ninja Leap", category:"Racing", tags:["racing","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Ninja%20Leap", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Ninja%20Leap", description:"Play Ninja Leap online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"pirate-cove", title:"Pirate Cove", category:"Shooter", tags:["shooter","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Pirate%20Cove", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Pirate%20Cove", description:"Play Pirate Cove online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"laser-grid", title:"Laser Grid", category:"Strategy", tags:["strategy","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Laser%20Grid", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Laser%20Grid", description:"Play Laser Grid online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"wizard-quest", title:"Wizard Quest", category:"Adventure", tags:["adventure","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Wizard%20Quest", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Wizard%20Quest", description:"Play Wizard Quest online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"block-blast", title:"Block Blast", category:"Platformer", tags:["platformer","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Block%20Blast", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Block%20Blast", description:"Play Block Blast online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"tank-battle", title:"Tank Battle", category:"Simulation", tags:["simulation","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Tank%20Battle", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Tank%20Battle", description:"Play Tank Battle online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"sky-runner", title:"Sky Runner", category:"RPG", tags:["rpg","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Sky%20Runner", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Sky%20Runner", description:"Play Sky Runner online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"gem-hunter", title:"Gem Hunter", category:"Sports", tags:["sports","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Gem%20Hunter", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Gem%20Hunter", description:"Play Gem Hunter online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"cyber-chase", title:"Cyber Chase", category:"Survival", tags:["survival","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Cyber%20Chase", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Cyber%20Chase", description:"Play Cyber Chase online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"zombie-wave", title:"Zombie Wave", category:"Multiplayer", tags:["multiplayer","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Zombie%20Wave", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Zombie%20Wave", description:"Play Zombie Wave online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"meteor-dodge", title:"Meteor Dodge", category:"Action", tags:["action","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Meteor%20Dodge", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Meteor%20Dodge", description:"Play Meteor Dodge online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"fish-tank", title:"Fish Tank", category:"Arcade", tags:["arcade","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Fish%20Tank", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Fish%20Tank", description:"Play Fish Tank online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"robot-arena", title:"Robot Arena", category:"Puzzle", tags:["puzzle","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Robot%20Arena", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Robot%20Arena", description:"Play Robot Arena online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"shadow-ninja", title:"Shadow Ninja", category:"Racing", tags:["racing","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Shadow%20Ninja", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Shadow%20Ninja", description:"Play Shadow Ninja online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"pixel-wars", title:"Pixel Wars", category:"Shooter", tags:["shooter","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Pixel%20Wars", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Pixel%20Wars", description:"Play Pixel Wars online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"endless-ocean", title:"Endless Ocean", category:"Strategy", tags:["strategy","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Endless%20Ocean", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Endless%20Ocean", description:"Play Endless Ocean online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"bubble-pop", title:"Bubble Pop", category:"Adventure", tags:["adventure","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Bubble%20Pop", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Bubble%20Pop", description:"Play Bubble Pop online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"race-kings", title:"Race Kings", category:"Platformer", tags:["platformer","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Race%20Kings", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Race%20Kings", description:"Play Race Kings online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"monster-truck", title:"Monster Truck", category:"Simulation", tags:["simulation","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Monster%20Truck", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Monster%20Truck", description:"Play Monster Truck online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"farm-life", title:"Farm Life", category:"RPG", tags:["rpg","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Farm%20Life", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Farm%20Life", description:"Play Farm Life online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"castle-siege", title:"Castle Siege", category:"Sports", tags:["sports","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Castle%20Siege", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Castle%20Siege", description:"Play Castle Siege online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"ice-runner", title:"Ice Runner", category:"Survival", tags:["survival","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Ice%20Runner", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Ice%20Runner", description:"Play Ice Runner online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"fire-trail", title:"Fire Trail", category:"Multiplayer", tags:["multiplayer","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Fire%20Trail", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Fire%20Trail", description:"Play Fire Trail online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"storm-rider", title:"Storm Rider", category:"Action", tags:["action","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Storm%20Rider", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Storm%20Rider", description:"Play Storm Rider online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"electric-maze", title:"Electric Maze", category:"Arcade", tags:["arcade","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Electric%20Maze", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Electric%20Maze", description:"Play Electric Maze online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"ancient-quest", title:"Ancient Quest", category:"Puzzle", tags:["puzzle","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Ancient%20Quest", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Ancient%20Quest", description:"Play Ancient Quest online for free.", featured:false, controls:"Mouse / Keyboard" },
  { id:"gravity-ball", title:"Gravity Ball", category:"Racing", tags:["racing","browser","fun"], thumbnail:"https://placehold.co/200x200/1a1a2e/ffffff?text=Gravity%20Ball", embedPath:"https://placehold.co/800x600/1a1a2e/ffffff?text=Gravity%20Ball", description:"Play Gravity Ball online for free.", featured:false, controls:"Mouse / Keyboard" }
];

const seen = new Set();
export const UNIQUE_GAMES = GAMES.filter(g => { if (seen.has(g.id)) return false; seen.add(g.id); return true; });
