export const CATEGORIES = ["All","Action","Apps","Arcade","Multiplayer","Platformer","Puzzle","Racing","RPG","Shooter","Sports","Strategy","Survival","Adventure","Simulation"];

export const GAMES = [
  // ── Featured Apps (open in overlay) ──────────────────────────────
  { id:"instagram", title:"Instagram",  category:"Apps",    tags:["social","photos","app","instagram"], thumbnail:"https://www.google.com/s2/favicons?domain=instagram.com&sz=128",  embedPath:"app:instagram", description:"Browse Instagram unblocked.",  featured:true, controls:"Mouse" },
  { id:"tiktok",    title:"TikTok",     category:"Apps",    tags:["social","video","app","tiktok"],   thumbnail:"https://www.google.com/s2/favicons?domain=tiktok.com&sz=128",     embedPath:"app:tiktok",    description:"Watch TikTok videos.",          featured:true, controls:"Mouse" },
  { id:"reddit",    title:"Reddit",     category:"Apps",    tags:["social","news","app","reddit"],   thumbnail:"https://www.google.com/s2/favicons?domain=reddit.com&sz=128",     embedPath:"app:reddit",    description:"Browse Reddit.",                featured:true, controls:"Mouse" },
  { id:"roblox",    title:"Roblox",     category:"Shooter", tags:["roblox","multiplayer","game","build"],thumbnail:"https://www.google.com/s2/favicons?domain=roblox.com&sz=128",  embedPath:"app:roblox",    description:"Play Roblox unblocked.",        featured:true, controls:"Mouse + Keyboard" },
// ── Slope family ───────────────────────────────────────────────
  { id:"slope",             title:"Slope",                   category:"Racing",      tags:["ball","speed","3d","endless","neon"],          thumbnail:"/logos/slope.jpg",          embedPath:"/games/slope.html",          description:"Race a ball down a neon slope at breakneck speed. One mistake and it's over.",      featured:true,  controls:"Arrow keys / WASD" },
  { id:"slopeplus",         title:"Slope+",                  category:"Racing",      tags:["ball","speed","3d","endless"],                  thumbnail:"/logos/slopeplus.png",       embedPath:"/games/slopeplus.html",      description:"The harder, faster version of Slope with extra obstacles.",                          featured:false, controls:"Arrow keys" },
  { id:"snowrider",         title:"Snow Rider 3D",           category:"Racing",      tags:["snow","sled","3d","endless","winter"],           thumbnail:"/logos/snowrider.jpg",       embedPath:"/games/snowrider.html",      description:"Dodge trees and rocks as you sled down an endless snowy mountain.",                  featured:true,  controls:"Arrow keys" },
  { id:"drifthunters",      title:"Drift Hunters",           category:"Racing",      tags:["drift","car","3d","upgrade"],                   thumbnail:"/logos/drifthunters.jpeg",   embedPath:"/games/drifthunters.html",   description:"Drift around tracks and earn cash to upgrade your ride.",                            featured:true,  controls:"WASD + Space" },
  { id:"motox3m",           title:"Moto X3M",                category:"Racing",      tags:["bike","stunt","physics"],                       thumbnail:"/logos/motox3m.png",         embedPath:"/games/motox3m.html",        description:"Pull off insane stunts on a physics-powered dirt bike.",                             featured:false, controls:"Arrow keys" },
  { id:"getaway",           title:"Getaway Shootout",        category:"Multiplayer", tags:["2player","ragdoll","race","funny"],              thumbnail:"/logos/getaway.png",         embedPath:"/games/getaway.html",        description:"Two players race to the getaway vehicle using chaotic physics.",                     featured:true,  controls:"WASD + P/O" },

  // ── 1v1 / Shooter ──────────────────────────────────────────────
  { id:"1v1lol",            title:"1v1.lol",                 category:"Shooter",     tags:["build","shoot","battle royale","multiplayer"],  thumbnail:"/logos/1v1.jpeg",            embedPath:"/games/1v1lol.html",         description:"Build structures and outshoot opponents in this fast-paced battle.",                 featured:true,  controls:"WASD + Mouse" },
  { id:"rooftopsnipers",    title:"Rooftop Snipers",         category:"Multiplayer", tags:["2player","sniper","physics","ragdoll"],          thumbnail:"/logos/rooftop.png",         embedPath:"/games/rooftopsnipers.html", description:"Knock your opponent off the rooftop with one well-placed shot.",                     featured:true,  controls:"W + P to shoot" },
  { id:"rooftopsnipers2",   title:"Rooftop Snipers 2",       category:"Multiplayer", tags:["2player","sniper","physics","sequel"],           thumbnail:"/logos/rooftop2.jpeg",       embedPath:"/games/rooftopsnipers2.html",description:"More maps and guns in the sniper rooftop sequel.",                                   featured:false, controls:"W + P to shoot" },
  { id:"funnyshooter2",     title:"Funny Shooter 2",         category:"Shooter",     tags:["fps","3d","silly","arena"],                     thumbnail:"/logos/funny-shooter-2.jpg", embedPath:"/games/funnyshooter2.html",  description:"FPS chaos where you shoot goofy ragdoll enemies in arenas.",                         featured:false, controls:"WASD + Mouse" },
  { id:"csgo",              title:"CS:GO Classic",           category:"Shooter",     tags:["fps","counterstrike","arena","retro"],           thumbnail:"/logos/csgo.jpeg",           embedPath:"/games/csgo.html",           description:"Classic Counter-Strike gameplay in your browser.",                                   featured:false, controls:"WASD + Mouse" },
  { id:"codmw4",            title:"CoD: Modern Warfare 4",   category:"Shooter",     tags:["fps","cod","multiplayer","action"],              thumbnail:"/logos/codmw4.png",          embedPath:"/games/codmw4.html",         description:"Modern Warfare-style FPS action in the browser.",                                    featured:false, controls:"WASD + Mouse" },

  // ── Platformer ─────────────────────────────────────────────────
  { id:"celeste",           title:"Celeste",                 category:"Platformer",  tags:["indie","hard","pixel","precision","mountain"],   thumbnail:"/logos/celeste.jpg",         embedPath:"/games/celeste.html",        description:"A brutally precise platformer about climbing a mountain and facing your inner demons.",featured:true, controls:"Arrow keys + Z/X/C" },
  { id:"hollow",            title:"Hollow Knight",           category:"Adventure",   tags:["metroidvania","indie","bug","dark","boss"],      thumbnail:"/logos/hollow.jpg",          embedPath:"/games/hollow.html",         description:"Explore a vast underground kingdom of insects in this acclaimed metroidvania.",      featured:true,  controls:"Arrow keys + Z/X/C" },
  { id:"silksong",          title:"Hollow Knight: Silksong", category:"Adventure",   tags:["metroidvania","sequel","silk","boss"],           thumbnail:"/logos/silksong.jpg",        embedPath:"/games/silksong.html",       description:"Play as Hornet in this anticipated sequel to Hollow Knight.",                        featured:true,  controls:"Arrow keys + Z/X/C" },
  { id:"ovo",               title:"OvO",                     category:"Platformer",  tags:["parkour","speedrun","minimalist","stickman"],    thumbnail:"/logos/ovo.png",             embedPath:"/games/ovo.html",            description:"Ultra-smooth stickman platformer built for speedrunning.",                           featured:true,  controls:"Arrow keys" },
  { id:"ovo2",              title:"OvO 2",                   category:"Platformer",  tags:["parkour","speedrun","sequel","stickman"],        thumbnail:"/logos/ovo2.webp",           embedPath:"/games/ovo2.html",           description:"Even more levels and mechanics in the parkour platformer sequel.",                   featured:false, controls:"Arrow keys" },
  { id:"vex",               title:"Vex",                     category:"Platformer",  tags:["stickman","obstacle","hard","precise"],          thumbnail:"/logos/vex.png",             embedPath:"/games/vex.html",            description:"Traverse deadly obstacle courses as a nimble stickman.",                             featured:false, controls:"WASD + Arrow keys" },
  { id:"vex2",              title:"Vex 2",                   category:"Platformer",  tags:["stickman","obstacle","hard","sequel"],           thumbnail:"/logos/vex2.jpeg",           embedPath:"/games/vex2.html",           description:"More devious traps and levels in the stickman obstacle series.",                     featured:false, controls:"WASD + Arrow keys" },
  { id:"vex3",              title:"Vex 3",                   category:"Platformer",  tags:["stickman","obstacle","hard","sequel"],           thumbnail:"/logos/vex3.png",             embedPath:"/games/vex3.html",           description:"Vex 3 brings water levels and new obstacles to the deadly series.",                  featured:false, controls:"WASD + Arrow keys" },
  { id:"fancypantsadventure",title:"Fancy Pants Adventure",  category:"Platformer",  tags:["stick","fluid","cartoon","classic"],             thumbnail:"/logos/fancy.png",           embedPath:"/games/fancypantsadventure.html",description:"Run and flip through hand-drawn worlds as the iconic Fancy Pants Man.",            featured:false, controls:"Arrow keys + S" },
  { id:"redball",           title:"Red Ball",                category:"Platformer",  tags:["ball","roll","physics","cute"],                  thumbnail:"/logos/redball.webp",        embedPath:"/games/redball.html",        description:"Roll the red ball through puzzle-platformer levels.",                               featured:false, controls:"Arrow keys" },
  { id:"supermario64",      title:"Super Mario 64",          category:"Platformer",  tags:["mario","nintendo","3d","classic","n64"],         thumbnail:"/logos/supermario64.jpg",    embedPath:"/games/supermario64.html",   description:"The legendary 3D platformer that defined a generation.",                            featured:true,  controls:"WASD + Mouse" },
  { id:"mariocombat",       title:"Mario Combat",            category:"Platformer",  tags:["mario","beat em up","classic"],                  thumbnail:"/logos/mariocombat.png",     embedPath:"/games/mariocombat.html",    description:"Mario takes on waves of Goombas in this retro beat-em-up.",                         featured:false, controls:"Arrow keys + A/S" },
  { id:"sonicthehedgehog",  title:"Sonic the Hedgehog",      category:"Platformer",  tags:["sonic","sega","speed","classic","retro"],        thumbnail:"/logos/sonic.jpeg",          embedPath:"/games/sonicthehedgehog.html",description:"The original speedy blue hedgehog in classic Sega Genesis form.",                  featured:true,  controls:"Arrow keys" },
  { id:"riddleschool",      title:"Riddle School",           category:"Puzzle",      tags:["point click","escape","school","flash"],         thumbnail:"/logos/riddle.jpeg",         embedPath:"/games/riddleschool.html",   description:"Point-and-click your way out of school in this beloved flash classic.",             featured:false, controls:"Mouse" },
  { id:"noobsteveparkour",  title:"Noob Steve Parkour",      category:"Platformer",  tags:["minecraft","parkour","pixel","noob"],            thumbnail:"/logos/noobsteveparkour.png",embedPath:"/games/noob-steve-parkour/index.html",description:"Parkour through Minecraft-inspired levels as Noob Steve.",                     featured:false, controls:"WASD + Space" },
  { id:"icedodo",           title:"Ice Dodo",                category:"Arcade",      tags:["cute","ice","endless","bird"],                   thumbnail:"/logos/icedodo.jpg",         embedPath:"/games/icedodo.html",        description:"Guide a cute dodo bird through icy obstacles.",                                     featured:false, controls:"Tap / Click" },

  // ── Retro Bowl family ──────────────────────────────────────────
  { id:"retrobowl",         title:"Retro Bowl",              category:"Sports",      tags:["football","retro","pixel","nfl","management"],   thumbnail:"/logos/unnamed.png",         embedPath:"/games/retrobowl.html",      description:"Manage and play a retro-style American football team to glory.",                    featured:true,  controls:"Mouse + Tap" },
  { id:"retrobowlcollege",  title:"Retro Bowl College",      category:"Sports",      tags:["football","college","retro","pixel"],            thumbnail:"/logos/retrobowl2.webp",     embedPath:"/games/retrobowlcollege.html",description:"Take a college football program to a national championship.",                     featured:false, controls:"Mouse + Tap" },

  // ── Sports ─────────────────────────────────────────────────────
  { id:"basketbros",        title:"Basketball Bros",         category:"Sports",      tags:["basketball","2player","funny","ragdoll"],        thumbnail:"/logos/basketbros.jpg",      embedPath:"/games/basketbros.html",     description:"Dunk on your friends in this hilarious 2-player basketball brawler.",               featured:true,  controls:"WASD + Arrow keys" },
  { id:"basketrandom",      title:"Basketball Random",       category:"Multiplayer", tags:["basketball","random","2player","ragdoll"],       thumbnail:"/logos/basket.png",          embedPath:"/games/basketrandom.html",   description:"Chaotic basketball with random physics and characters every round.",                 featured:false, controls:"W + Up" },
  { id:"basketstars",       title:"Basket Stars",            category:"Sports",      tags:["basketball","swipe","mobile","street"],          thumbnail:"/logos/basketstars.jpg",     embedPath:"/games/basketstars.html",    description:"Score creative baskets with swipe shots in Basket Stars.",                          featured:false, controls:"Mouse drag" },
  { id:"boxingrandom",      title:"Boxing Random",           category:"Multiplayer", tags:["boxing","2player","ragdoll","physics","funny"],  thumbnail:"/logos/boxing.png",          embedPath:"/games/boxingrandom.html",   description:"Two ragdoll boxers fight with random physics in every round.",                       featured:false, controls:"W + Up" },
  { id:"volleyrandom",      title:"Volleyball Random",       category:"Multiplayer", tags:["volleyball","2player","ragdoll","physics"],      thumbnail:"/logos/volley.png",          embedPath:"/games/volleyrandom.html",   description:"Random physics volleyball with hilarious ragdoll characters.",                      featured:false, controls:"W + Up" },
  { id:"footbros",          title:"Football Bros",           category:"Sports",      tags:["football","2player","soccer","brawl"],           thumbnail:"/logos/footbros.jpg",        embedPath:"/games/footbros.html",       description:"Fast-paced 2-player football brawler with power moves.",                            featured:false, controls:"WASD + Arrow keys" },
  { id:"basebros",          title:"Base Bros",               category:"Sports",      tags:["baseball","2player","ragdoll"],                  thumbnail:"/logos/basebros.jpg",        embedPath:"/games/basebros.html",       description:"Swing for the fences in this 2-player baseball brawler.",                           featured:false, controls:"WASD + Arrow keys" },
  { id:"gladd",             title:"Gladdiahoppers",          category:"Multiplayer", tags:["gladiator","2player","arena","fight"],           thumbnail:"/logos/gladdihoppers.jpg",   embedPath:"/games/gladd.html",          description:"Fight as gladiators in this chaotic 2-player arena brawler.",                       featured:false, controls:"WASD + Arrow keys" },
  { id:"fifa11",            title:"FIFA 11",                 category:"Sports",      tags:["soccer","fifa","classic","football"],            thumbnail:"/logos/fifa11.jpg",          embedPath:"/games/fifa11.html",         description:"Classic FIFA 11 soccer in your browser.",                                           featured:false, controls:"Arrow keys + A/S/D" },
  { id:"supa",              title:"Super Smash Bros",        category:"Multiplayer", tags:["smash","nintendo","fight","2player","brawl"],    thumbnail:"/logos/supersmashbros.jpg",  embedPath:"/games/supa.html",           description:"Play Super Smash Bros characters in a browser brawler.",                            featured:true,  controls:"WASD + Arrow keys" },

  // ── Subway Surfers ─────────────────────────────────────────────
  { id:"subwaysurfersmiami",title:"Subway Surfers: Miami",   category:"Arcade",      tags:["runner","subway","mobile","endless","surf"],     thumbnail:"/logos/subwaymiami.webp",    embedPath:"/games/subwaysurfersmiami.html",description:"Surf through Miami's vibrant subway system.",                                    featured:true,  controls:"Arrow keys / Swipe" },
  { id:"subwaysurferswinterholiday",title:"Subway Surfers: Winter",category:"Arcade", tags:["runner","subway","winter","endless","surf"],    thumbnail:"/logos/wintersurf.webp",     embedPath:"/games/subwaysurferswinterholiday.html",description:"The classic runner in a snowy winter holiday setting.",                       featured:false, controls:"Arrow keys / Swipe" },

  // ── Puzzle ─────────────────────────────────────────────────────
  { id:"geometrydash",      title:"Geometry Dash",           category:"Arcade",      tags:["rhythm","jump","music","hard","timing"],         thumbnail:"/logos/geometry.png",        embedPath:"/games/geometrydash.html",   description:"Jump to the rhythm and dodge obstacles in this music-based runner.",                featured:true,  controls:"Click / Spacebar" },
  { id:"geodash_gba_port",  title:"Geometry Dash GBA",       category:"Arcade",      tags:["rhythm","retro","gba","geometry"],               thumbnail:"/logos/geodashdemake.png",   embedPath:"/games/geodash_gba_port/index.html",description:"Geometry Dash reimagined as a Game Boy Advance demake.",                      featured:false, controls:"Click / Z" },
  { id:"cookie",            title:"Cookie Clicker",          category:"Simulation",  tags:["idle","clicker","incremental","cookies"],        thumbnail:"/logos/cookieclicker.jpg",   embedPath:"/games/cookie.html",         description:"Click cookies to build the biggest cookie empire possible.",                        featured:true,  controls:"Mouse click" },
  { id:"tinyfishing",       title:"Tiny Fishing",            category:"Simulation",  tags:["fishing","idle","chill","cast"],                  thumbnail:"/logos/tiny-fishing-square-icon.png",embedPath:"/games/tinyfishing.html",description:"Cast your line and reel in tiny fish to upgrade your gear.",                  featured:true,  controls:"Mouse click" },
  { id:"linerider",         title:"Line Rider",              category:"Puzzle",      tags:["draw","physics","sled","creative","sandbox"],    thumbnail:"/logos/linerider.png",       embedPath:"/games/linerider.html",      description:"Draw lines and watch a sledder ride them with realistic physics.",                  featured:false, controls:"Mouse draw" },
  { id:"fruitninja",        title:"Fruit Ninja",             category:"Arcade",      tags:["slice","fruit","swipe","mobile","reflex"],       thumbnail:"/logos/fruit.webp",          embedPath:"/games/fruitninja.html",     description:"Slice fruit before it falls off the screen. Miss three and you're done.",           featured:false, controls:"Mouse swipe" },
  { id:"nutsnbolts",        title:"Nuts n Bolts",            category:"Puzzle",      tags:["physics","puzzle","screw","wrench"],              thumbnail:"/logos/nuts.png",            embedPath:"/games/nutsnbolts.html",     description:"Solve physics-based puzzles by fitting nuts and bolts together.",                   featured:false, controls:"Mouse" },
  { id:"badtime",           title:"Undertale: Bad Time",     category:"RPG",         tags:["undertale","sans","boss","bullet hell","dodge"], thumbnail:"/logos/badtime.webp",        embedPath:"/games/badtime.html",        description:"Survive Sans's legendary bad time boss fight from Undertale.",                      featured:true,  controls:"Arrow keys + Z/X" },
  { id:"unfairundyne",      title:"Unfair Undyne",           category:"RPG",         tags:["undertale","undyne","boss","dodge","hard"],      thumbnail:"/logos/Undyne_face.webp",    embedPath:"/games/unfairundyne.html",   description:"Face an impossibly hard version of Undyne's spear attacks.",                        featured:false, controls:"Arrow keys + Z/X" },
  { id:"webglfluidsimulation",title:"WebGL Fluid Simulation",category:"Simulation",  tags:["fluid","interactive","sandbox","art","chill"],   thumbnail:"/logos/webglfluidsimulation.png",embedPath:"/games/webgl-fluid-simulation/index.html",description:"Mesmerizing interactive fluid simulation you can swirl with your finger.", featured:false, controls:"Mouse / Touch" },

  // ── Among Us / IO ──────────────────────────────────────────────
  { id:"amongus",           title:"Among Us",                category:"Multiplayer", tags:["impostor","social","deduction","space","vote"], thumbnail:"/logos/Among_Us.webp",       embedPath:"/games/amongus.html",        description:"Find the impostor aboard the spaceship before it's too late.",                      featured:true,  controls:"WASD + Click" },
  { id:"agario",            title:"Agar.io",                 category:"Multiplayer", tags:["io","blob","eat","grow","multiplayer","online"],  thumbnail:"/logos/agario.jpg",         embedPath:"/games/agario.html",         description:"Eat smaller cells to grow bigger while avoiding larger ones.",                      featured:true,  controls:"Mouse" },
  { id:"paperio",           title:"Paper.io",                category:"Multiplayer", tags:["io","territory","snake","multiplayer","online"], thumbnail:"/logos/paperio.jpg",         embedPath:"/games/paperio.html",        description:"Claim territory and cut off rivals in this addictive .io game.",                    featured:false, controls:"Arrow keys" },
  { id:"crossyroads",       title:"Crossy Road",             category:"Arcade",      tags:["frogger","hop","mobile","endless","cute"],       thumbnail:"/logos/Crossy_Road_icon.jpeg",embedPath:"/games/crossyroads.html",   description:"Hop across roads and rivers endlessly without getting squished.",                   featured:false, controls:"Arrow keys / WASD" },

  // ── Indie / Narrative ──────────────────────────────────────────
  { id:"omori",             title:"Omori",                   category:"RPG",         tags:["rpg","indie","horror","narrative","dream"],      thumbnail:"/logos/omori.jpeg",          embedPath:"/games/omori.html",          description:"Explore a surreal dream world hiding deep secrets in this indie RPG.",              featured:true,  controls:"Arrow keys + Z/X/C" },
  { id:"deltarune",         title:"Deltarune",               category:"RPG",         tags:["undertale","rpg","kris","dark world","indie"],   thumbnail:"/logos/deltarune.webp",      embedPath:"/games/deltarune.html",      description:"Undertale creator Toby Fox's latest RPG – chapters 1 & 2.",                        featured:true,  controls:"Arrow keys + Z/X" },
  { id:"oneshot",           title:"OneShot",                 category:"Adventure",   tags:["rpg","meta","lightbulb","puzzle","narrative"],   thumbnail:"/logos/oneshot.jpg",         embedPath:"/games/oneshot.html",        description:"A game that knows you're playing it. You only get one shot.",                       featured:false, controls:"Arrow keys + Z" },
  { id:"yume",              title:"Yume Nikki",              category:"Adventure",   tags:["rpg","surreal","dream","explore","japanese"],    thumbnail:"/logos/yume-nikki.webp",     embedPath:"/games/yume.html",           description:"Wander through a dream-girl's surreal, disturbing subconscious.",                  featured:false, controls:"Arrow keys + Z" },
  { id:"bind",              title:"The Binding of Isaac",    category:"Roguelike",   tags:["roguelike","dungeon","dark","random","boss"],    thumbnail:"/logos/binding.jpg",         embedPath:"/games/bind.html",           description:"Descend into a procedurally generated basement full of monsters.",                  featured:true,  controls:"WASD + Arrow keys" },
  { id:"celeste2",          title:"Celeste Classic",         category:"Platformer",  tags:["pico8","celeste","hard","pixel","precision"],    thumbnail:"/logos/celeste.jpg",         embedPath:"/games/celeste.html",        description:"The original PICO-8 prototype that became the full game.",                          featured:false, controls:"Arrow keys + Z/X" },

  // ── FNAF ───────────────────────────────────────────────────────
  { id:"fnaf",              title:"Five Nights at Freddy's", category:"Survival",    tags:["horror","fnaf","animatronic","night","scary"],   thumbnail:"/logos/fnaf.jpg",            embedPath:"/games/fnaf.html",           description:"Survive five nights as a security guard at Freddy Fazbear's Pizza.",                featured:true,  controls:"Mouse" },
  { id:"fnaf2",             title:"FNAF 2",                  category:"Survival",    tags:["horror","fnaf","animatronic","sequel","scary"],  thumbnail:"/logos/fnaf2.jpg",           embedPath:"/games/fnaf2.html",          description:"The old animatronics are back and there are new ones too.",                          featured:false, controls:"Mouse" },
  { id:"fnaf3",             title:"FNAF 3",                  category:"Survival",    tags:["horror","fnaf","springtrap","sequel"],           thumbnail:"/logos/fnaf3.jpg",           embedPath:"/games/fnaf3.html",          description:"One animatronic remains in the FNAF horror series: Springtrap.",                    featured:false, controls:"Mouse" },
  { id:"fnaf4",             title:"FNAF 4",                  category:"Survival",    tags:["horror","fnaf","nightmare","bedroom","sequel"],  thumbnail:"/logos/fnaf4.jpg",           embedPath:"/games/fnaf4.html",          description:"The most frightening FNAF yet – nightmare animatronics in your home.",              featured:false, controls:"Mouse" },
  { id:"baldibasics",       title:"Baldi's Basics",          category:"Survival",    tags:["horror","baldi","school","teacher","creepy"],   thumbnail:"/logos/baldi.png",           embedPath:"/games/baldibasics.html",    description:"Collect notebooks while avoiding the terrifyingly fast Baldi.",                     featured:true,  controls:"Mouse + WASD" },
  { id:"granny",            title:"Granny",                  category:"Survival",    tags:["horror","escape","stealth","granny"],           thumbnail:"/logos/granny.jpg",          embedPath:"/games/granny.html",         description:"Escape the house without waking up Granny. She hears everything.",                  featured:false, controls:"Mouse + WASD" },
  { id:"granny2",           title:"Granny 2",                category:"Survival",    tags:["horror","escape","stealth","granny","sequel"],   thumbnail:"/logos/granny2.jpg",         embedPath:"/games/granny2.html",        description:"Two enemies now stalk you in this expanded horror escape sequel.",                   featured:false, controls:"Mouse + WASD" },

  // ── Pokemon ─────────────────────────────────────────────────────
  { id:"pokemonemerald",    title:"Pokemon Emerald",         category:"RPG",         tags:["pokemon","gba","hoenn","emerald","classic"],    thumbnail:"/logos/emerald.jpg",         embedPath:"/games/pokemonemerald.html", description:"The definitive Hoenn region Pokemon experience on Game Boy Advance.",               featured:true,  controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonfirered",    title:"Pokemon Fire Red",        category:"RPG",         tags:["pokemon","gba","kanto","firered","classic"],    thumbnail:"/logos/pokefire.jpg",         embedPath:"/games/pokemonfirered.html", description:"Experience the Kanto region remake for Game Boy Advance.",                          featured:false, controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonleafgreen",  title:"Pokemon Leaf Green",      category:"RPG",         tags:["pokemon","gba","kanto","leafgreen"],            thumbnail:"/logos/leafgreen.jpg",        embedPath:"/games/pokemonleafgreen.html",description:"The Leaf Green version of the Kanto region remake.",                              featured:false, controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonruby",       title:"Pokemon Ruby",            category:"RPG",         tags:["pokemon","gba","hoenn","ruby"],                 thumbnail:"/logos/ruby.png",             embedPath:"/games/pokemonruby.html",    description:"Explore the Hoenn region for the first time in Pokemon Ruby.",                      featured:false, controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonstadium",    title:"Pokemon Stadium",         category:"RPG",         tags:["pokemon","n64","stadium","3d","battle"],        thumbnail:"/logos/stadium.webp",         embedPath:"/games/pokemonstadium.html", description:"Battle in 3D in the classic Nintendo 64 Pokemon Stadium.",                          featured:false, controls:"Arrow keys + Z/X" },
  { id:"pokemonunbound",    title:"Pokemon Unbound",         category:"RPG",         tags:["pokemon","hack","gba","custom","hard"],         thumbnail:"/logos/pokeunbound.webp",     embedPath:"/games/pokemonunbound.html", description:"A fan-made Pokemon hack with a new region, story, and 800+ Pokemon.",               featured:true,  controls:"Arrow keys + Z/X/A/S" },
  { id:"pokemonemeraldrg",  title:"Pokemon Emerald Rogue",   category:"RPG",         tags:["pokemon","roguelike","emerald","hack"],         thumbnail:"/logos/rouge.png",            embedPath:"/games/pokemonemeraldrg.html",description:"Roguelike Pokemon Emerald with randomized routes and items every run.",         featured:false, controls:"Arrow keys + Z/X/A/S" },

  // ── Retro / Classic ─────────────────────────────────────────────
  { id:"doom",              title:"Doom",                    category:"Shooter",     tags:["fps","retro","demon","classic","id"],            thumbnail:"/logos/doom.jpeg",           embedPath:"/games/doom.html",           description:"The original 1993 FPS that defined first-person shooters.",                         featured:true,  controls:"WASD + Mouse" },
  { id:"metal",             title:"Metal Slug",              category:"Action",      tags:["run n gun","retro","arcade","classic","neo geo"],thumbnail:"/logos/metal.jpg",           embedPath:"/games/metal.html",          description:"Run, gun, and rescue POWs in this legendary arcade run-n-gun.",                     featured:true,  controls:"Arrow keys + A/S/D" },
  { id:"mariokart64",       title:"Mario Kart 64",           category:"Racing",      tags:["mario","n64","kart","classic","multiplayer"],    thumbnail:"/logos/mariokart.jpeg",       embedPath:"/games/mariokart64.html",    description:"Race as Mario characters on the iconic N64 tracks.",                                featured:true,  controls:"Arrow keys + Z/X" },
  { id:"metroidfusion",     title:"Metroid Fusion",          category:"Adventure",   tags:["metroid","gba","samus","fusion","metroidvania"],  thumbnail:"/logos/metroid.jpg",        embedPath:"/games/metroidfusion.html",  description:"Samus hunts parasitic X organisms aboard a research station.",                      featured:false, controls:"Arrow keys + Z/X/A" },
  { id:"ocarina",           title:"Ocarina of Time",         category:"Adventure",   tags:["zelda","n64","link","ocarina","3d","classic"],   thumbnail:"/logos/ocorina.jpg",          embedPath:"/games/ocarina.html",        description:"Link's first 3D adventure to stop Ganondorf from conquering Hyrule.",               featured:true,  controls:"WASD + Mouse" },
  { id:"sonicthehedgehog2", title:"Sonic the Hedgehog",      category:"Platformer",  tags:["sonic","sega","speed","retro","classic"],        thumbnail:"/logos/sonic.jpeg",           embedPath:"/games/sonicthehedgehog.html",description:"Speed through Green Hill Zone in the original Sega classic.",                     featured:false, controls:"Arrow keys" },

  // ── Indie horror / Narrative ───────────────────────────────────
  { id:"silent",            title:"Silent Hill",             category:"Survival",    tags:["horror","fog","ps1","classic","survival"],      thumbnail:"/logos/silent.jpg",           embedPath:"/games/silent.html",         description:"Wander the fog-covered streets of Silent Hill in the PS1 classic.",                 featured:false, controls:"Arrow keys" },
  { id:"oblivoneve",        title:"Oblivion Eve",            category:"Adventure",   tags:["rpg","indie","dark","oblivion"],                thumbnail:"/logos/oblivion.png",         embedPath:"/games/oblivoneve.html",     description:"An indie RPG inspired by the dark world of Oblivion.",                             featured:false, controls:"Mouse + WASD" },
  { id:"kinder",            title:"Kindergarten",            category:"Adventure",   tags:["dark comedy","school","story","choice","indie"],thumbnail:"/logos/kinder.jpg",           embedPath:"/games/kinder.html",         description:"Survive a very messed-up day at kindergarten.",                                     featured:false, controls:"Mouse + Arrow keys" },
  { id:"kinder2",           title:"Kindergarten 2",          category:"Adventure",   tags:["dark comedy","school","story","sequel","indie"],thumbnail:"/logos/kinder2.jpg",          embedPath:"/games/kinder2.html",        description:"More dark kindergarten chaos in the sequel.",                                       featured:false, controls:"Mouse + Arrow keys" },
  { id:"kinder3",           title:"Kindergarten 3",          category:"Adventure",   tags:["dark comedy","school","story","sequel","indie"],thumbnail:"/logos/kinder3.jpg",          embedPath:"/games/kinder3.html",        description:"The trilogy continues at the most dangerous school ever.",                          featured:false, controls:"Mouse + Arrow keys" },

  // ── Misc Action / Arcade ──────────────────────────────────────
  { id:"ultrakill",         title:"Ultrakill",               category:"Action",      tags:["fps","fast","stylish","cyberpunk","blood"],      thumbnail:"/logos/ultrakill.jpeg",       embedPath:"/games/ultrakill.html",      description:"Feed on blood to heal and go as fast as possible in this stylish FPS.",             featured:true,  controls:"WASD + Mouse" },
  { id:"awesome",           title:"Awesome Tanks 2",         category:"Action",      tags:["tank","top down","shooter","upgrade"],           thumbnail:"/logos/awesome.jpg",          embedPath:"/games/awesome.html",        description:"Blast through levels and upgrade your tank in this top-down shooter.",              featured:false, controls:"WASD + Mouse" },
  { id:"hazard",            title:"Hazard",                  category:"Action",      tags:["shooter","action","top down"],                  thumbnail:"/logos/hazard.png",           embedPath:"/games/hazard.html",         description:"Top-down shooter with hazardous environments.",                                     featured:false, controls:"WASD + Mouse" },
  { id:"karl",              title:"Karl",                    category:"Arcade",      tags:["puzzle","funny","physics","karl"],               thumbnail:"/logos/karl.jpg",             embedPath:"/games/karl.html",           description:"Help Karl navigate puzzles in this quirky physics game.",                           featured:false, controls:"Mouse" },
  { id:"clash",             title:"Clash Royale",            category:"Strategy",    tags:["card","tower defense","supercell","real time"],  thumbnail:"/logos/clash.jpg",            embedPath:"/games/clash.html",          description:"Build decks and destroy the enemy king's tower in real-time card battles.",         featured:false, controls:"Mouse / Touch" },
  { id:"taiseiproject",     title:"Taisei Project",          category:"Shooter",     tags:["bullet hell","touhou","shmup","anime"],          thumbnail:"/logos/taisei.png",           embedPath:"/games/taiseiproject.html",  description:"An open-source Touhou-inspired bullet hell with stunning patterns.",                 featured:false, controls:"Arrow keys + Z/X/Shift" },
  { id:"theycomin",         title:"They Are Coming",         category:"Strategy",    tags:["zombie","tower defense","wave","click"],         thumbnail:"/logos/theyarecoming.jpg",    embedPath:"/games/theycomin.html",      description:"Survive endless waves of zombies using upgrades and strategy.",                      featured:false, controls:"Mouse" },
  { id:"jet",               title:"Jetpack Joyride",         category:"Arcade",      tags:["jetpack","endless","mobile","coins","classic"],  thumbnail:"/logos/jetpack.jpg",          embedPath:"/games/jet.html",            description:"Strap on a jetpack and dodge electric beams in this endless runner.",               featured:true,  controls:"Click / Spacebar" },
  { id:"snow",              title:"Snow Battle",             category:"Action",      tags:["snowball","fight","winter","action"],            thumbnail:"/logos/snowbattle.jpg",       embedPath:"/games/snow.html",           description:"Pelt your opponents with snowballs in an icy arena.",                               featured:false, controls:"Mouse + WASD" },

  // ── Eaglercraft / Minecraft ────────────────────────────────────
  { id:"eaglercraft122",    title:"Eaglercraft 1.22",        category:"Adventure",   tags:["minecraft","browser","survival","build","craft"],thumbnail:"/logos/eagler.png",          embedPath:"/games/eaglercraft122.html", description:"Full Minecraft experience running directly in your browser.",                        featured:true,  controls:"WASD + Mouse" },

  // ── Celeste / Indie ────────────────────────────────────────────
  { id:"fnf",               title:"Friday Night Funkin'",    category:"Arcade",      tags:["rhythm","music","rap","battle","funkin"],       thumbnail:"/logos/fnf.webp",             embedPath:"/games/fnf.html",            description:"Battle musical foes in this rhythm rap showdown.",                                  featured:true,  controls:"Arrow keys / WASD" },
  { id:"bitlife",           title:"BitLife",                 category:"Simulation",  tags:["life","sim","choices","text","casual"],          thumbnail:"/logos/bitlife.png",          embedPath:"/games/bitlife.html",        description:"Live countless virtual lives full of choices in this text-based life sim.",          featured:true,  controls:"Mouse / Touch" },

  // ── New DotGUI extras ─────────────────────────────────────────
  { id:"ballistic-chickens",title:"Ballistic Chickens",      category:"Action",      tags:["chickens","launch","physics","silly","arcade"],  thumbnail:"/logos/ballisticchickens.png",embedPath:"/games/ballistic-chickens/index.html",description:"Launch ballistic chickens at targets in this physics shooter.", featured:false, controls:"Mouse" },
  { id:"ctr",               title:"Crash Team Racing",       category:"Racing",      tags:["crash","kart","ps1","classic","race"],           thumbnail:"/logos/ctr.png",              embedPath:"/games/ctr/index.html",      description:"Race as Crash Bandicoot and friends in the classic kart racer.",                     featured:true,  controls:"Arrow keys + Z/X" },
  { id:"ctr-tr",            title:"CTR: Time Reckoning",     category:"Racing",      tags:["crash","kart","time trial","race"],              thumbnail:"/logos/ctrtr.png",            embedPath:"/games/ctr-tr/index.html",   description:"Time trial version of Crash Team Racing for speedrunners.",                         featured:false, controls:"Arrow keys + Z/X" },
  { id:"ltf3",              title:"Little Town Fishing 3",   category:"Simulation",  tags:["fishing","chill","little town","idle"],          thumbnail:"/logos/ltf3.png",             embedPath:"/games/ltf3/index.html",     description:"Relaxing fishing in Little Town, the third installment.",                           featured:false, controls:"Mouse" },
  { id:"there-is-no-game",  title:"There Is No Game",        category:"Puzzle",      tags:["meta","fourth wall","funny","puzzle","unique"],  thumbnail:"/logos/thereisnogame.png",    embedPath:"/games/there-is-no-game/index.html",description:"A game that insists there is no game. Click around to find out.",            featured:true,  controls:"Mouse + Click" },
  { id:"twitch-tetris",     title:"Twitch Tetris",           category:"Puzzle",      tags:["tetris","block","twitch","classic","puzzle"],    thumbnail:"/logos/twitchtetris.png",     embedPath:"/games/twitch-tetris/index.html",description:"Classic Tetris-style block puzzle with a twist.",                              featured:false, controls:"Arrow keys" },

  // ── Extra popular games ────────────────────────────────────────
  { id:"deltarune-ch2",     title:"Deltarune Ch. 2",         category:"RPG",         tags:["undertale","rpg","sequel","kris","cyber"],       thumbnail:"/logos/deltarune.webp",       embedPath:"/games/deltarune.html",      description:"Chapter 2 continues Kris's journey into the Dark World.",                          featured:false, controls:"Arrow keys + Z/X" },
  { id:"celeste-ch2",       title:"Celeste Classic 2",       category:"Platformer",  tags:["pico8","celeste","sequel","hard","precision"],   thumbnail:"/logos/celeste.jpg",          embedPath:"/games/celeste.html",        description:"The follow-up to the original PICO-8 Celeste classic.",                            featured:false, controls:"Arrow keys + Z/X" },

  // ── Games from SHS (real thumbnails, hosted on GitHub Pages) ─────
  { id:"shs-2048",           title:"2048",                    category:"Puzzle",      tags:["2048","number","puzzle","brain","classic"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/2048.jpg",            embedPath:"https://gras2027.github.io/SHS/2048/index.html",            description:"Slide and merge tiles to reach the 2048 tile.",                                     featured:false, controls:"Arrow keys / Swipe" },
  { id:"shs-wordle",         title:"Wordle",                  category:"Puzzle",      tags:["wordle","word","guess","daily"],                 thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/wordle.jpg",          embedPath:"https://gras2027.github.io/SHS/wordle/index.html",          description:"Guess the hidden 5-letter word in 6 tries.",                                        featured:true,  controls:"Keyboard" },
  { id:"shs-dogeminer",      title:"DogeMiner",               category:"Simulation",  tags:["clicker","idle","doge","mine","crypto"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/dog.jpg",             embedPath:"https://gras2027.github.io/SHS/DogeMiner/index.html",       description:"Click to mine Dogecoin and build your lunar empire.",                               featured:false, controls:"Mouse" },
  { id:"shs-survev",         title:"Survev.io",               category:"Multiplayer", tags:["io","battle royale","shooting","online"],        thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/survev.png",          embedPath:"https://gras2027.github.io/SHS/survevio.html",              description:"Battle royale .io game – be the last one standing.",                               featured:true,  controls:"WASD + Mouse" },
  { id:"shs-snake",          title:"Snake",                   category:"Arcade",      tags:["snake","classic","grow","grid"],                 thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/snake.jpg",           embedPath:"https://gras2027.github.io/SHS/snake/index.html",           description:"Eat dots to grow longer without hitting yourself.",                                 featured:false, controls:"Arrow keys / WASD" },
  { id:"shs-cell-machine",   title:"Cell Machine",            category:"Puzzle",      tags:["cell","automata","logic","sandbox"],             thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/cell.jpg",            embedPath:"https://gras2027.github.io/SHS/cell/index.html",            description:"Create cellular automata machines and watch them evolve.",                          featured:false, controls:"Mouse" },
  { id:"shs-touch",          title:"Touch",                   category:"Arcade",      tags:["touch","reaction","tap","reflex"],               thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/touch.jpg",           embedPath:"https://gras2027.github.io/SHS/touch/index.html",           description:"Test your reflexes in this fast-paced arcade game.",                               featured:false, controls:"Click / Tap" },
  { id:"shs-tunnel-rush",    title:"Tunnel Rush",             category:"Arcade",      tags:["tunnel","dodge","fast","neon","endless"],        thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/tunnel.jpg",          embedPath:"https://gras2027.github.io/SHS/tunnelrush/index.html",      description:"Dodge obstacles as you fly through a neon tunnel at warp speed.",                   featured:true,  controls:"Arrow keys / A-D" },
  { id:"shs-tetris",         title:"Tetris",                  category:"Puzzle",      tags:["tetris","block","classic","puzzle","stack"],     thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/tetris.jpg",          embedPath:"https://gras2027.github.io/SHS/tetris/index.html",          description:"The legendary block-stacking puzzle game.",                                         featured:true,  controls:"Arrow keys" },
  { id:"shs-happy-wheels",   title:"Happy Wheels",            category:"Action",      tags:["ragdoll","gore","physics","vehicle","brutal"],   thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/happy.jpg",           embedPath:"https://gras2027.github.io/SHS/happy/index.html",           description:"Ride vehicles through deadly obstacle courses in this brutal physics game.",         featured:true,  controls:"Arrow keys + Ctrl" },
  { id:"shs-robogo",         title:"RoboGo",                  category:"Platformer",  tags:["robot","platformer","dodge","obstacle"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/robogo.jpg",          embedPath:"https://gras2027.github.io/SHS/robogo/index.html",          description:"Guide a robot through tricky platformer levels.",                                   featured:false, controls:"Arrow keys" },
  { id:"shs-soccer-random",  title:"Soccer Random",           category:"Sports",      tags:["soccer","football","random","2player","funny"],  thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/soccer.jpg",          embedPath:"https://gras2027.github.io/SHS/soccer-random/index.html",  description:"Chaotic 2-player soccer with random physics every round.",                          featured:false, controls:"W + Up" },
  { id:"shs-portaboy",       title:"PortaBoy",                category:"Arcade",      tags:["retro","arcade","handheld","mini games"],        thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/porta.jpg",           embedPath:"https://gras2027.github.io/SHS/portaboy/index.html",        description:"Collection of handheld-style mini arcade games.",                                   featured:false, controls:"Arrow keys + Z/X" },
  { id:"shs-sword",          title:"Sword",                   category:"Action",      tags:["sword","fight","action","duel"],                 thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/sword.jpg",           embedPath:"https://gras2027.github.io/SHS/sword/index.html",           description:"Pick up the sword and battle enemies in this action game.",                         featured:false, controls:"Mouse" },
  { id:"shs-knife-hit",      title:"Knife Hit",               category:"Arcade",      tags:["knife","throw","precision","spin"],              thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/knife.jpg",           embedPath:"https://gras2027.github.io/SHS/knifehit/index.html",        description:"Throw knives at a spinning log without hitting other knives.",                      featured:false, controls:"Click / Tap" },
  { id:"shs-breaklock",      title:"BreakLock",               category:"Puzzle",      tags:["pattern","lock","memory","logic"],               thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/lock.jpg",            embedPath:"https://gras2027.github.io/SHS/breaklock/index.html",       description:"Crack the pattern lock by memorising and recreating sequences.",                    featured:false, controls:"Mouse / Touch" },
  { id:"shs-bison",          title:"Bison",                   category:"Action",      tags:["action","fight","arena","bison"],                thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/bison.jpg",           embedPath:"https://gras2027.github.io/SHS/bison/index.html",           description:"Fight your way through enemies in this intense action game.",                       featured:false, controls:"WASD + Mouse" },
  { id:"shs-doodle-jump",    title:"Doodle Jump",             category:"Arcade",      tags:["jump","endless","platform","mobile","classic"],  thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/doodle.jpg",          embedPath:"https://gras2027.github.io/SHS/doodle/index.html",          description:"Jump from platform to platform as high as you can go.",                             featured:true,  controls:"Arrow keys / Tilt" },
  { id:"shs-adcap",          title:"AdVenture Capitalist",    category:"Simulation",  tags:["idle","clicker","capitalist","business"],        thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/adcap.jpg",           embedPath:"https://gras2027.github.io/SHS/adcap/index.html",           description:"Start with a lemonade stand and build a business empire.",                          featured:false, controls:"Mouse" },
  { id:"shs-baldi",          title:"Baldi's Basics",          category:"Survival",    tags:["horror","school","baldi","escape","creepy"],     thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/baldi.jpg",           embedPath:"https://gras2027.github.io/SHS/baldi/index.html",           description:"Collect notebooks while avoiding the terrifyingly fast Baldi.",                     featured:false, controls:"WASD + Mouse" },
  { id:"shs-bball-legends",  title:"Basketball Legends",      category:"Sports",      tags:["basketball","legends","2player","sports"],       thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/basketballL.jpg",     embedPath:"https://gras2027.github.io/SHS/basketball-legends/index.html",description:"Play as NBA legends in this 2-player basketball game.",                           featured:true,  controls:"WASD + Arrow keys" },
  { id:"shs-boxing2",        title:"Boxing Physics 2",        category:"Multiplayer", tags:["boxing","physics","2player","ragdoll"],          thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/boxing2.jpg",         embedPath:"https://gras2027.github.io/SHS/boxing-physics2/index.html", description:"Chaotic ragdoll boxing with wild physics.",                                          featured:false, controls:"W + Up" },
  { id:"shs-burger",         title:"Burger Game",             category:"Simulation",  tags:["burger","cooking","build","stack"],              thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/burger.jpg",          embedPath:"https://gras2027.github.io/SHS/burger/index.html",          description:"Stack and serve burgers in this satisfying cooking game.",                          featured:false, controls:"Mouse" },
  { id:"shs-chrome-dino",    title:"Chrome Dino",             category:"Arcade",      tags:["dino","chrome","endless","classic","jump"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/chromedino.jpg",      embedPath:"https://gras2027.github.io/SHS/chrome-dino/index.html",     description:"The iconic Google Chrome dinosaur endless runner.",                                 featured:false, controls:"Spacebar / Up" },
  { id:"shs-doodle-god",     title:"Doodle God",              category:"Puzzle",      tags:["alchemy","combine","elements","puzzle","craft"], thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/doodlegod.jpg",       embedPath:"https://gras2027.github.io/SHS/doodlegod/index.html",       description:"Combine elements to create the entire universe piece by piece.",                    featured:true,  controls:"Mouse" },
  { id:"shs-dreader",        title:"Dreader",                 category:"Survival",    tags:["horror","dark","escape","survival"],             thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/dreader.jpg",         embedPath:"https://gras2027.github.io/SHS/dreader/index.html",         description:"Survive the darkness in this creepy horror experience.",                            featured:false, controls:"Mouse + WASD" },
  { id:"shs-drift",          title:"Drift Race",              category:"Racing",      tags:["drift","car","race","top-down"],                 thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/drift.jpg",           embedPath:"https://gras2027.github.io/SHS/drift/index.html",           description:"Drift around tracks for maximum style points.",                                     featured:false, controls:"Arrow keys" },
  { id:"shs-exhibit",        title:"Exhibit of Sorrows",      category:"Survival",    tags:["horror","art","museum","dark","creepy"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/ex2.jpg",             embedPath:"https://gras2027.github.io/SHS/exhibit/index.html",         description:"Explore a deeply unsettling art exhibit that gets darker the further you go.",      featured:false, controls:"Mouse + WASD" },
  { id:"shs-freezeria",      title:"Papa's Freezeria",        category:"Simulation",  tags:["papas","cooking","ice cream","serving"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/freezeria.jpg",       embedPath:"https://gras2027.github.io/SHS/freezeria/index.html",       description:"Scoop, blend, and top ice cream sundaes to serve your customers.",                  featured:true,  controls:"Mouse" },
  { id:"shs-friendly-fire",  title:"Friendly Fire",           category:"Action",      tags:["action","2player","shoot","cowboy"],             thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/fire.jpg",            embedPath:"https://gras2027.github.io/SHS/friendlyfire/index.html",    description:"2-player cowboy shootout with friendly fire enabled.",                              featured:false, controls:"WASD + Arrow keys" },
  { id:"shs-greybox",        title:"Greybox",                 category:"Puzzle",      tags:["puzzle","logic","greybox","minimal"],            thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/greybox.jpg",         embedPath:"https://gras2027.github.io/SHS/greybox/index.html",         description:"A minimalist puzzle game about rearranging grey boxes.",                            featured:false, controls:"Mouse" },
  { id:"shs-slither",        title:"Slither.io",              category:"Multiplayer", tags:["io","snake","grow","online","multiplayer"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/slither.jpg",         embedPath:"https://gras2027.github.io/SHS/slither.io-clone-master/slither-container.html",description:"Slither and grow by eating others in this classic .io game.", featured:true, controls:"Mouse" },
  { id:"shs-mario-run",      title:"Mario Run",               category:"Platformer",  tags:["mario","run","autorun","mobile","platformer"],   thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/mario2.jpg",          embedPath:"https://gras2027.github.io/SHS/Mario.Run-master/index.html",description:"Mario auto-runs through levels – tap to jump over obstacles.",                     featured:false, controls:"Click / Spacebar" },
  { id:"shs-hill-climb",     title:"Hill Climb Racing",       category:"Racing",      tags:["hill","climb","physics","car","fuel"],           thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/brand.jpg",           embedPath:"https://gras2027.github.io/SHS/Hill-master/index.html",     description:"Drive over hills and mountains without flipping your vehicle.",                     featured:true,  controls:"Arrow keys" },
  { id:"shs-suika",          title:"Suika Game",              category:"Puzzle",      tags:["suika","fruit","merge","drop","japanese"],       thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/suika.webp",          embedPath:"https://gras2027.github.io/SHS/suika-game-main-2/index.html",description:"Drop and merge fruits to create bigger fruits in this relaxing puzzle.",           featured:true,  controls:"Mouse / Touch" },
  { id:"shs-infinite-cars",  title:"Infinite Cars",           category:"Racing",      tags:["car","infinite","race","endless"],               thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/infinity.jpg",        embedPath:"https://gras2027.github.io/SHS/infinite-cars-main/index.html",description:"Race endlessly and avoid infinite traffic in a scrolling car game.",              featured:false, controls:"Arrow keys" },
  { id:"shs-smb",            title:"Super Mario Bros",        category:"Platformer",  tags:["mario","nintendo","classic","platformer","nes"],  thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/mario.jpg",          embedPath:"https://gras2027.github.io/SHS/Super-Mario-Bros-master/index.html",description:"The original Super Mario Bros on the NES, playable in your browser.",          featured:true,  controls:"Arrow keys + Z/X" },
  { id:"shs-road",           title:"Road",                    category:"Racing",      tags:["road","car","dodge","traffic"],                  thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/road.jpg",            embedPath:"https://gras2027.github.io/SHS/Road-master/index.html",     description:"Navigate traffic on a fast-moving road.",                                           featured:false, controls:"Arrow keys" },
  { id:"shs-cut-rope",       title:"Cut the Rope",            category:"Puzzle",      tags:["cut","rope","candy","physics","om nom"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/cut.jpg",             embedPath:"https://gras2027.github.io/SHS/CutTheRope-master/index.html",description:"Cut ropes to swing candy into Om Nom's mouth.",                                   featured:true,  controls:"Mouse / Touch" },
  { id:"shs-highway",        title:"Highway Traffic",         category:"Racing",      tags:["highway","traffic","dodge","car"],               thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/highway.jpg",         embedPath:"https://gras2027.github.io/SHS/highway/index.html",         description:"Weave through highway traffic at high speed.",                                      featured:false, controls:"Arrow keys" },
  { id:"shs-territorial",    title:"Territorial.io",          category:"Strategy",    tags:["io","territory","war","map","strategy"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/territorial.jpg",     embedPath:"https://gras2027.github.io/SHS/teritorial/static/index.html",description:"Expand your territory and conquer the map in this .io strategy game.",           featured:true,  controls:"Mouse" },
  { id:"shs-fbwg",           title:"Fireboy & Watergirl",     category:"Multiplayer", tags:["fireboy","watergirl","coop","2player","puzzle"],  thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/firewater.jpg",       embedPath:"https://gras2027.github.io/SHS/fireboy_watergirl/index.html",description:"Work together as Fireboy and Watergirl to solve elemental puzzles.",             featured:true,  controls:"WASD + Arrow keys" },
  { id:"shs-lose95",         title:"Lose 95",                 category:"Arcade",      tags:["retro","windows","parody","point click"],        thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/95.jpg",              embedPath:"https://gras2027.github.io/SHS/lose95/index.html",          description:"A satirical Windows 95-style game where you try to lose.",                          featured:false, controls:"Mouse" },
  { id:"shs-monkey-mart",    title:"Monkey Mart",             category:"Simulation",  tags:["monkey","mart","supermarket","idle","shop"],     thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/monkey.jpg",          embedPath:"https://gras2027.github.io/SHS/monkey/index.html",          description:"Grow produce and run a supermarket as a cute monkey.",                              featured:true,  controls:"Mouse / WASD" },
  { id:"shs-stickman-hook",  title:"Stickman Hook",           category:"Arcade",      tags:["stickman","swing","hook","spider","skill"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/stick.jpg",           embedPath:"https://gras2027.github.io/SHS/Stickmanhook/index.html",    description:"Swing from hook to hook as a stickman in this addictive game.",                    featured:true,  controls:"Click / Hold" },
  { id:"shs-dogeminer2",     title:"DogeMiner 2",             category:"Simulation",  tags:["clicker","idle","doge","sequel","moon"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/doge2.jpg",           embedPath:"https://gras2027.github.io/SHS/Dogeminer2/index.html",      description:"Mine Doge and travel to the moon in this idle sequel.",                             featured:false, controls:"Mouse" },
  { id:"shs-yohoho",         title:"YoHoHo.io",               category:"Multiplayer", tags:["pirate","io","battle","sword","multiplayer"],    thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/yohoho.jpg",          embedPath:"https://gras2027.github.io/SHS/yohoho/index.html",          description:"Battle other pirates on a shrinking island in this .io game.",                     featured:false, controls:"Mouse" },
  { id:"shs-whg2",           title:"World's Hardest Game 2",  category:"Arcade",      tags:["hard","dodge","impossible","maze","skill"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/hard.jpg",            embedPath:"https://gras2027.github.io/SHS/worlds-hardest-game-2/index.html",description:"The legendary impossible maze game. Don't touch red.",                           featured:true,  controls:"Arrow keys / WASD" },
  { id:"shs-missiles",       title:"Missiles",                category:"Arcade",      tags:["missile","dodge","arcade","reflex"],             thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/miss.jpg",            embedPath:"https://gras2027.github.io/SHS/Missiles/index.html",        description:"Dodge waves of incoming missiles in this fast arcade game.",                        featured:false, controls:"Mouse / Arrow keys" },
  { id:"shs-drive-mad",      title:"Drive Mad",               category:"Racing",      tags:["drive","mad","physics","vehicle","obstacles"],   thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/drivemad.jpg",        embedPath:"https://gras2027.github.io/SHS/DriveMad/index.html",        description:"Drive vehicles over insane physics obstacles without toppling over.",               featured:true,  controls:"Arrow keys" },
  { id:"shs-aquapark",       title:"Aquapark Slides",         category:"Arcade",      tags:["waterslide","aqua","race","casual"],             thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/aqaua.jpg",           embedPath:"https://gras2027.github.io/SHS/aquapark-slides/index.html", description:"Race down twisting water slides to the finish.",                                    featured:false, controls:"Mouse / Touch" },
  { id:"shs-sticky-road",    title:"Sticky Road",             category:"Racing",      tags:["sticky","road","physics","car","hill"],          thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/stickyroad.jpg",      embedPath:"https://gras2027.github.io/SHS/sticky-road/index.html",     description:"Drive on a sticky road that defies gravity.",                                       featured:false, controls:"Arrow keys" },
  { id:"shs-blumgi",         title:"Blumgi Magic Ball",       category:"Arcade",      tags:["ball","magic","bounce","puzzle","physics"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/magicball.jpg",       embedPath:"https://gras2027.github.io/SHS/BlumgiMagicBall/index.html", description:"Launch a magic ball to hit targets in this satisfying physics game.",               featured:false, controls:"Mouse" },
  { id:"shs-head-soccer",    title:"Head Soccer 2022",        category:"Sports",      tags:["soccer","head","football","2player","funny"],    thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/headsoccer.jpg",      embedPath:"https://gras2027.github.io/SHS/HeadSoccer2022/index.html",  description:"Score goals with your oversized head in this fun soccer game.",                    featured:false, controls:"WASD + Arrow keys" },
  { id:"shs-stick-duel",     title:"Stick Duel",              category:"Action",      tags:["stick","duel","2player","fight","ragdoll"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/stickduel.jpg",       embedPath:"https://gras2027.github.io/SHS/stickduel/index.html",       description:"Duel against a stickman opponent in a lethal arena.",                              featured:false, controls:"WASD + Arrow keys" },
  { id:"shs-fbwg2",          title:"Fireboy & Watergirl 2",   category:"Multiplayer", tags:["fireboy","watergirl","coop","2player","sequel"], thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/fireboywatergirl.jpg",embedPath:"https://gras2027.github.io/SHS/Fireboy-and-Watergirl-main/index.html",description:"More co-op puzzles for Fireboy and Watergirl in the ice temple.", featured:false, controls:"WASD + Arrow keys" },
  { id:"shs-pizzeria",       title:"Papa's Pizzeria",         category:"Simulation",  tags:["papas","cooking","pizza","serving"],             thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_pizzeria.jpg",      embedPath:"https://gras2027.github.io/SHS/papas/papas_pizzeria.html",  description:"Take orders and bake perfectly topped pizzas for customers.",                       featured:false, controls:"Mouse" },
  { id:"shs-bakeria",        title:"Papa's Bakeria",          category:"Simulation",  tags:["papas","cooking","pie","baking"],                thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_bakeria.jpg",       embedPath:"https://gras2027.github.io/SHS/papas/papas-bakeria.html",   description:"Bake pies to order in Papa's Bakeria.",                                             featured:false, controls:"Mouse" },
  { id:"shs-burgeria",       title:"Papa's Burgeria",         category:"Simulation",  tags:["papas","cooking","burger","serving"],            thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_burgeria.jpg",      embedPath:"https://gras2027.github.io/SHS/papas/papas-burgeria.html",  description:"Flip and build burgers for a line of hungry customers.",                            featured:false, controls:"Mouse" },
  { id:"shs-cheeseria",      title:"Papa's Cheeseria",        category:"Simulation",  tags:["papas","cooking","grilled cheese","serving"],    thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_cheeseria.jpg",     embedPath:"https://gras2027.github.io/SHS/papas/papas-cheeseria.html", description:"Grill the perfect cheese sandwiches for your customers.",                           featured:false, controls:"Mouse" },
  { id:"shs-cupcakeria",     title:"Papa's Cupcakeria",       category:"Simulation",  tags:["papas","cooking","cupcake","baking"],            thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_cupcakeria.jpg",    embedPath:"https://gras2027.github.io/SHS/papas/papas-cupcakeria.html",description:"Bake and decorate cupcakes for everyone in Cupcakeria.",                         featured:false, controls:"Mouse" },
  { id:"shs-donuteria",      title:"Papa's Donuteria",        category:"Simulation",  tags:["papas","cooking","donut","fry","decorate"],      thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_donuteria.jpg",     embedPath:"https://gras2027.github.io/SHS/papas/papas-donuteria.html", description:"Fry and decorate custom donuts in Papa's Donuteria.",                               featured:false, controls:"Mouse" },
  { id:"shs-hotdog",         title:"Papa's Hot Doggeria",     category:"Simulation",  tags:["papas","cooking","hotdog","baseball"],           thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_hot.jpg",           embedPath:"https://gras2027.github.io/SHS/papas/papas-hot-doggeria.html",description:"Serve hot dogs and popcorn at a baseball stadium.",                              featured:false, controls:"Mouse" },
  { id:"shs-pastaria",       title:"Papa's Pastaria",         category:"Simulation",  tags:["papas","cooking","pasta","italian"],             thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_pastaria.jpg",      embedPath:"https://gras2027.github.io/SHS/papas/papas-pastaria.html",  description:"Cook and plate fresh pasta dishes in Papa's Pastaria.",                             featured:false, controls:"Mouse" },
  { id:"shs-sushiria",       title:"Papa's Sushiria",         category:"Simulation",  tags:["papas","cooking","sushi","roll"],                thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_shushiria.jpg",     embedPath:"https://gras2027.github.io/SHS/papas/papas-sushiria.html",  description:"Roll and serve custom sushi orders in Papa's Sushiria.",                            featured:false, controls:"Mouse" },
  { id:"shs-tacomia",        title:"Papa's Taco Mia",         category:"Simulation",  tags:["papas","cooking","taco","mexican"],              thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_taco.jpg",          embedPath:"https://gras2027.github.io/SHS/papas/papas-taco-mia.html",  description:"Cook and wrap tacos for hungry customers in Taco Mia.",                             featured:false, controls:"Mouse" },
  { id:"shs-wingeria",       title:"Papa's Wingeria",         category:"Simulation",  tags:["papas","cooking","wings","fry","sauce"],         thumbnail:"https://raw.githubusercontent.com/gras2027/SHS/main/images/p_wingeria.jpg",      embedPath:"https://gras2027.github.io/SHS/papas/papas-wingeria.html",  description:"Fry and sauce chicken wings to order in Papa's Wingeria.",                          featured:false, controls:"Mouse" },
];

const seen = new Set();
export const UNIQUE_GAMES = GAMES.filter(g => { if (seen.has(g.id)) return false; seen.add(g.id); return true; });
